import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { Window } from 'happy-dom';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { eq } from 'drizzle-orm';
import { migrateTestDb } from '../../../scripts/migrate-test-db.js';
import { createApp } from '../../api/src/app.js';
import { catalogueRepository } from '../../api/src/catalogue.js';
import { orderRepository } from '../../api/src/orders.js';
import { adminRepository } from '../../api/src/admin-repository.js';
import { mediaStore } from '../../api/src/media.js';
import { emailService,type CommerceDb } from '../../api/src/email.js';
import { customerService } from '../../api/src/customers.js';
import { returnService } from '../../api/src/returns.js';
import { hashPassword } from '../../api/src/password.js';
import { seedData } from '../../api/src/seed-data.js';
import * as s from '../../api/src/schema.js';

test('customer UI registers, verifies a guest order, submits cancellation, follows admin review and resets its password',{timeout:30000},async()=>{
 const window=new Window({url:'http://localhost:4321/account/'}),globals=['window','document','navigator','location','history','HTMLElement','HTMLInputElement','HTMLSelectElement','HTMLTextAreaElement','MutationObserver','Event','InputEvent','localStorage','sessionStorage','getComputedStyle'];const descriptors=new Map(globals.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));for(const key of globals)Object.defineProperty(globalThis,key,{value:key==='window'?window:key==='getComputedStyle'?window.getComputedStyle.bind(window):(window as any)[key],writable:true,configurable:true});(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;(window as any).confirm=()=>true;
 const originalFetch=globalThis.fetch,pg=new PGlite();await migrateTestDb(pg);const db=drizzle(pg,{schema:s}) as unknown as CommerceDb;await seedData(db,JSON.parse(await readFile(new URL('../../../database/seeds.json',import.meta.url),'utf8')));await db.insert(s.adminUsers).values({id:'account-ui-admin',email:'owner@example.test',name:'Owner',passwordHash:await hashPassword('Admin-password-12345')});const orders=orderRepository(db,{mode:'test',pinPrefixes:[]}),mail=emailService(db,{driver:'local',siteUrl:'http://localhost:4321',encryptionKey:'a'.repeat(64),from:'store@example.test',production:false}),customers=customerService(db,mail,orders),returns=returnService(db,orders);
 const app=await createApp(catalogueRepository(db),{rateLimit:false,orders,mail,returns,customers:{service:customers,production:false,sameSite:'lax',sessionHours:24,emailMode:'local'},admin:{repo:adminRepository(db),production:false,sameSite:'lax',sessionHours:8,media:mediaStore({driver:'local',localDir:'.data/unused-account-ui',publicUrl:'http://localhost:3001/media',production:false})}});
 const adminLogin=await app.inject({method:'POST',url:'/api/v1/admin/login',headers:{origin:'http://localhost:4321'},payload:{email:'owner@example.test',password:'Admin-password-12345'}});const jar=new Map<string,string>();const adminCookie=String(adminLogin.headers['set-cookie']).split(';')[0];jar.set(adminCookie.split('=')[0],adminCookie.split('=')[1]);
 const placed=await app.inject({method:'POST',url:'/api/v1/orders',headers:{origin:'http://localhost:4321'},payload:{expectedMode:'test',checkoutKey:randomUUID(),receiptSecret:randomBytes(32).toString('hex'),items:[{variantId:'variant-1',quantity:1}],coupon:'',giftWrap:false,delivery:'standard',paymentMethod:'cod',customer:{name:'Account Customer',email:'customer@example.test',phone:'9876543210'},address:{line1:'123 Test Street',line2:'',city:'Bengaluru',state:'Karnataka',postalCode:'560001',country:'IN'},expectedTotalPaise:87800}});assert.equal(placed.statusCode,201);
 globalThis.fetch=async(input,init)=>{const url=new URL(String(input)),r=await app.inject({method:(init?.method||'GET') as 'GET'|'POST',url:url.pathname+url.search,payload:init?.body?String(init.body):undefined,headers:{origin:'http://localhost:4321','content-type':'application/json',...(init?.headers as Record<string,string>),...(init?.credentials==='include'?{cookie:[...jar].map(([k,v])=>k+'='+v).join('; ')}:{})}});const setCookie=r.headers['set-cookie'];if(setCookie)for(const entry of Array.isArray(setCookie)?setCookie:[setCookie]){const pair=String(entry).split(';')[0],split=pair.indexOf('='),key=pair.slice(0,split),value=pair.slice(split+1);if(value)jar.set(key,value);else jar.delete(key);}if(init?.signal?.aborted)throw new DOMException('Aborted','AbortError');return new Response(r.body,{status:r.statusCode,headers:{'content-type':'application/json'}});};
 const {createElement:h,act}=await import('react'),{createRoot}=await import('react-dom/client'),{default:Account}=await import('../src/components/CustomerAccount.js'),{default:Emails}=await import('../src/components/AdminEmails.js'),{default:Returns}=await import('../src/components/AdminReturns.js');const container=window.document.createElement('div');window.document.body.append(container);const root=createRoot(container as any);let adminError='';
 const settle=async(check:()=>boolean)=>{for(let i=0;i<200;i++){await act(async()=>{await new Promise(r=>setTimeout(r,10));});if(check())return;}assert.fail('Account flow did not reach state: '+container.textContent);};
 const button=(text:string)=>[...container.querySelectorAll('button')].find(b=>b.textContent===text)!;
 const fill=async(label:string,value:string)=>{const field=[...container.querySelectorAll('label')].find(l=>l.textContent?.startsWith(label))?.querySelector('input,textarea');assert.ok(field,'Missing '+label);await act(async()=>{const prototype=field.tagName==='TEXTAREA'?window.HTMLTextAreaElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value')!.set!.call(field,value);field.dispatchEvent(new window.Event('input',{bubbles:true}));});};
 const submit=async(selector='.account-auth form')=>act(async()=>container.querySelector(selector)!.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true})));
 const mount=async(Component:any,props:any={})=>{await act(async()=>root.render(null));await act(async()=>root.render(h(Component,props)));};
 async function emailLink(kind:string){await mount(Emails,{csrf:adminLogin.json().csrfToken,writer:true,onError:(e:Error)=>{adminError=e.message;}});await settle(()=>!!button('Process queued emails'));await act(async()=>button('Process queued emails').click());await settle(()=>[...container.querySelectorAll('tr')].some(row=>row.textContent?.includes(kind)&&row.querySelector('button')));const row=[...container.querySelectorAll('tr')].find(r=>r.textContent?.includes(kind))!;await act(async()=>row.querySelector('button')!.click());await settle(()=>!!container.querySelector('.email-preview a'));const link=container.querySelector('.email-preview a')!.getAttribute('href')!;assert.equal(adminError,'');return link;}
 try{
  await mount(Account);await settle(()=>!!button('Create account'));await act(async()=>button('Create account').click());await fill('Your name','Account Customer');await fill('Email','customer@example.test');await fill('Password','Account-password-12345');await fill('Confirm password','Account-password-12345');await submit();await settle(()=>container.textContent?.includes('verification email has been queued')===true);
  await fill('Password','Account-password-12345');await submit();await settle(()=>container.textContent?.includes('Verification required')===true);assert.ok(!container.textContent?.includes(placed.json().number));
  const verifyLink=await emailLink('Verify your email');window.location.hash=verifyLink.split('#')[1];await mount(Account);await settle(()=>!!button('Verify email'));assert.equal(window.location.hash,'');await submit();await settle(()=>container.textContent?.includes('Email verified')===true);await settle(()=>!!container.querySelector('.account-order-list button'));
  await act(async()=>container.querySelector('.account-order-list')!.querySelector('button')!.click());await settle(()=>!!container.querySelector('.return-form'));await fill('Reason','Please cancel this full test order');await submit('.return-form');await settle(()=>container.textContent?.includes('Cancellation · requested')===true);
  await mount(Returns,{csrf:adminLogin.json().csrfToken,writer:true,onError:(e:Error)=>{adminError=e.message;}});await settle(()=>!!button('View request'));await act(async()=>button('View request').click());await settle(()=>!!button('Approve'));await act(async()=>button('Approve').click());await settle(()=>!!button('Close request'));await act(async()=>button('Close request').click());await settle(()=>container.textContent?.includes('cancel · closed')===true);assert.equal(adminError,'');assert.equal((await db.select().from(s.inventory).where(eq(s.inventory.variantId,'variant-1')))[0].available,12);
  await mount(Account);await settle(()=>!!container.querySelector('.account-order-list button'));await act(async()=>container.querySelector('.account-order-list')!.querySelector('button')!.click());await settle(()=>container.textContent?.includes('Cancellation · closed')===true);await act(async()=>button('Sign out').click());await settle(()=>!!container.querySelector('.account-auth'));await act(async()=>button('Forgot password').click());await fill('Email','customer@example.test');await submit();await settle(()=>container.textContent?.includes('password-reset email has been queued')===true);
  const resetLink=await emailLink('Reset your password');window.location.hash=resetLink.split('#')[1];await mount(Account);await settle(()=>!!button('Set new password'));await fill('Password','New-password-12345');await fill('Confirm password','New-password-12345');await submit();await settle(()=>container.textContent?.includes('Password reset. Sign in')===true);await fill('Email','customer@example.test');await fill('Password','New-password-12345');await submit();await settle(()=>container.textContent?.includes('Hello, Account Customer')===true);assert.ok(!window.localStorage.getItem('customer-password'));assert.equal((await db.select().from(s.returnRequests))[0].state,'closed');
 }finally{await act(async()=>root.unmount());await app.close();await pg.close();globalThis.fetch=originalFetch;for(const key of globals){const d=descriptors.get(key);if(d)Object.defineProperty(globalThis,key,d);else delete (globalThis as any)[key];}delete (globalThis as any).IS_REACT_ACT_ENVIRONMENT;await window.happyDOM.close();}
});
