import { useEffect,useState } from 'react';
import { z } from 'zod';
import { adminReturnRecordSchema,returnReviewSchema,money } from '@store/contracts';
import { request } from '../lib/api';
export default function AdminReturns({csrf,writer,onError}:{csrf:string,writer:boolean,onError:(e:unknown)=>void}){
 type Record=ReturnType<typeof adminReturnRecordSchema.parse>;type Action=ReturnType<typeof returnReviewSchema.parse>['action'];
 const [items,setItems]=useState<Record[]>([]),[selected,setSelected]=useState<Record|null>(null),[response,setResponse]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setItems(await request('/api/v1/admin/returns',z.array(adminReturnRecordSchema),{credentials:'include',cache:'no-store'}));}
 useEffect(()=>{load().catch(onError);},[]);
 async function action(action:Action){if(!selected||busy)return;const prompts:Partial<{[K in Action]:string}>={refund:'Initiate the full Razorpay TEST refund? Repeated checks will reconcile this same request.',restock:'Confirm every item has been inspected and is suitable for resale? Stock will be restored once.', 'manual-refund':'Confirm that the full COD refund was actually paid externally (or simulated for this test order)? This action does not transfer money.', 'adopt-refund':'Link this existing provider refund only after verifying its ID? No new refund will be issued.',close:'Close this request? An approved unpaid cancellation will cancel the order and restore stock once.'};if(prompts[action]&&!window.confirm(prompts[action]))return;setBusy(true);setMessage('');try{const next=await request('/api/v1/admin/returns/'+selected.id+'/review',adminReturnRecordSchema,{method:'POST',credentials:'include',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({version:selected.version,action,response,reference}),signal:AbortSignal.timeout(30000)});setSelected(next);setResponse('');setReference('');setMessage('Request updated.');await load();}catch(e){onError(e);}finally{setBusy(false);}}
 function actions(r:Record):Action[]{const available:Action[]=[];if(r.state==='requested')available.push('approve','reject');if(r.kind==='return'&&r.state==='approved')available.push('receive');if(!r.restocked&&((r.kind==='cancel'&&['approved','refunded','closed'].includes(r.state))||(r.kind==='return'&&['received','refund_pending','refunded','closed'].includes(r.state))))available.push('restock');if(r.amountPaise>0&&((r.kind==='cancel'&&r.state==='approved')||(r.kind==='return'&&r.state==='received')))available.push('refund','manual-refund','adopt-refund');if(r.state==='refund_pending')available.push('check','adopt-refund');if(r.state==='refunded'||r.amountPaise===0&&['approved','received'].includes(r.state))available.push('close');return available;}
 const labels:{[K in Action]:string}={approve:'Approve',reject:'Reject',receive:'Mark items received',restock:'Restock inspected items',refund:'Initiate online test refund',check:'Check provider refund','manual-refund':'Confirm external COD refund','adopt-refund':'Link existing provider refund',close:'Close request'};
 return <><div className="admin-page-heading"><h1>Returns & refunds</h1><button className="secondary" disabled={busy} onClick={()=>load().catch(onError)}>Refresh requests</button></div><p className="muted">Full-order requests only. Approval does not refund or restock. Customer-facing responses below are visible in the receipt and email.</p>{message&&<p className="admin-success" role="status">{message}</p>}<div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Request</th><th>Status</th><th>Amount</th><th>Action</th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td>{r.number}{r.mode==='test'&&<small> · Test</small>}</td><td>{r.kind}</td><td>{r.state.replaceAll('_',' ')}</td><td>{money(r.amountPaise)}</td><td><button className="secondary" onClick={()=>{setSelected(r);setResponse('');setReference('');setMessage('');}}>View request</button></td></tr>)}</tbody></table>{!items.length&&<p>No requests yet.</p>}</div>{selected&&<section className="admin-panel"><h2>{selected.number}</h2><p><strong>{selected.kind} · {selected.state}</strong></p><p>Reason: {selected.reason}</p><p>Refund amount: {money(selected.amountPaise)} · Provider state: {selected.refundState}</p><p>Restocked: {selected.restocked?'Yes':'No'}</p>{selected.refundId&&<p>Provider refund: {selected.refundId}</p>}{selected.manualReference&&<p>External COD refund reference: {selected.manualReference}</p>}{selected.refundIssue&&<p className="error">{selected.refundIssue}</p>}{selected.response&&<p>Previous response: {selected.response}</p>}<ol className="admin-activity">{selected.events.map(e=><li key={e.id}><strong>{e.state}</strong><p>{e.note}</p><small>{new Date(e.createdAt).toLocaleString()}</small></li>)}</ol>{writer&&<><label className="return-label">Customer-facing response<textarea maxLength={1000} value={response} onChange={e=>setResponse(e.target.value)}/></label><label className="return-label">External COD payment reference / existing provider refund ID<input maxLength={120} value={reference} onChange={e=>setReference(e.target.value)} placeholder="No bank account or card details"/></label><div className="admin-actions">{actions(selected).map(a=><button className="secondary" key={a} disabled={busy} onClick={()=>{void action(a);}}>{labels[a]}</button>)}</div></>}</section>}</>;
}
