import { useEffect,useState } from 'react';
import { mailListSchema,mailPreviewSchema } from '@store/contracts';
import { request } from '../lib/api';
import { messageSchema } from '../lib/customer-api';
export default function AdminEmails({csrf,writer,onError}:{csrf:string,writer:boolean,onError:(e:unknown)=>void}){
 const [items,setItems]=useState<ReturnType<typeof mailListSchema.parse>>([]),[preview,setPreview]=useState<ReturnType<typeof mailPreviewSchema.parse>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setItems(await request('/api/v1/admin/emails',mailListSchema,{credentials:'include',cache:'no-store'}));}
 useEffect(()=>{load().catch(onError);},[]);
 async function process(){setBusy(true);try{const result=await request('/api/v1/admin/emails/process',messageSchema,{method:'POST',credentials:'include',headers:{'X-CSRF-Token':csrf},body:'{}'});setMessage(result.message);await load();}catch(e){onError(e);}finally{setBusy(false);}}
 return <><div className="admin-page-heading"><h1>Emails</h1><div className="admin-actions"><button className="secondary" disabled={busy} onClick={()=>load().catch(onError)}>Refresh</button>{writer&&<button className="primary" disabled={busy} onClick={()=>{void process();}}>Process queued emails</button>}</div></div>{message&&<p className="admin-success" role="status">{message}</p>}<p className="muted">Queued email survives restarts. Local mode provides previews; provider mode submits messages. “Sent” means provider acceptance, not confirmed inbox delivery.</p><div className="admin-panel admin-table-wrap"><table className="admin-table"><thead><tr><th>Recipient / subject</th><th>Status</th><th>Attempts</th><th>Actions</th></tr></thead><tbody>{items.map(m=><tr key={m.id}><td><strong>{m.subject}</strong><p>{m.recipient}</p>{m.issue&&<p>{m.issue}</p>}</td><td>{m.state}</td><td>{m.attempts}</td><td>{writer&&m.previewAvailable&&<button className="secondary" disabled={busy} onClick={()=>{setBusy(true);request('/api/v1/admin/emails/'+m.id+'/preview',mailPreviewSchema,{credentials:'include',cache:'no-store'}).then(setPreview).catch(onError).finally(()=>setBusy(false));}}>View preview</button>}</td></tr>)}</tbody></table>{!items.length&&<p>No email queued yet.</p>}</div>{preview&&<section className="admin-panel email-preview"><h2>{preview.subject}</h2><p>To: {preview.recipient}</p><pre>{preview.text}</pre>{[...preview.text.matchAll(/\/account\/#((?:verify|reset)=[a-f0-9]{64})/g)].map((m,i)=><p key={i}><a className="secondary" href={'/account/#'+m[1]} target="_blank" rel="noreferrer">Open account link</a></p>)}<button className="text-button" onClick={()=>setPreview(null)}>Close preview</button></section>}</>;
}
