import { useEffect,useState } from 'react';
import { Plus,Trash2,ArrowUp,ArrowDown,Upload,Save,ExternalLink } from 'lucide-react';
import { adminProductInputSchema,imageUrlSchema,type AdminProduct,type AdminProductInput } from '@store/contracts';
import { adminApi,explainAdminError } from '../lib/admin-api';
export const slugify=(value:string)=>value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
type VariantForm={id?:string,sku:string,label:string,price:string,original:string,colour:string,material:string,gender:string,stock:string};
const blankVariant=():VariantForm=>({sku:'',label:'Default',price:'',original:'',colour:'Gold',material:'',gender:'For Her',stock:'0'});
export default function AdminProductEditor({initial,categories,csrf,onSaved,onCancel,onCategories,onExpired,readOnly=false}:{initial?:AdminProduct,categories:{slug:string,name:string}[],csrf:string,onSaved:(p:AdminProduct)=>void,onCancel:()=>void,onCategories:()=>void,onExpired:()=>void,readOnly?:boolean}){
 const [name,setName]=useState(initial?.name||''),[slug,setSlug]=useState(initial?.slug||''),[description,setDescription]=useState(initial?.description||''),[active,setActive]=useState(initial?.active??false),[rank,setRank]=useState(String(initial?.featuredRank??0)),[selected,setSelected]=useState(initial?.categories||[]),[images,setImages]=useState(initial?.images||[]);
 const [variants,setVariants]=useState<VariantForm[]>(initial?.variants.map(v=>({id:v.id,sku:v.sku,label:v.label,price:String(v.pricePaise/100),original:v.compareAtPaise?String(v.compareAtPaise/100):'',colour:v.colour,material:v.material,gender:v.gender,stock:String(v.stock)}))||[blankVariant()]);
 const [url,setUrl]=useState(''),[categoryName,setCategoryName]=useState(''),[categorySlug,setCategorySlug]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[dirty,setDirty]=useState(false),[categoryBusy,setCategoryBusy]=useState(false);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();Reflect.set(e,'returnValue','');};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function change(fn:()=>void){fn();setDirty(true);}
 function fail(e:unknown){if((e as any).code==='UNAUTHORIZED'){onExpired();return;}setError(explainAdminError(e));}
 const updateVariant=(index:number,key:keyof VariantForm,value:string)=>change(()=>setVariants(items=>items.map((v,i)=>i===index?{...v,[key]:value}:v)));
 async function save(){
  setError('');const input={name,slug,description,active,featuredRank:Number(rank),categories:selected,images,variants:variants.map(v=>({...(v.id?{id:v.id}:{}),sku:v.sku,label:v.label,pricePaise:v.price.trim()?Math.round(Number(v.price)*100):0,compareAtPaise:v.original.trim()?Math.round(Number(v.original)*100):null,colour:v.colour,material:v.material,gender:v.gender,stock:Number(v.stock)}))};
  const parsed=adminProductInputSchema.safeParse(input);if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '));return;}
  setBusy(true);try{const p=await adminApi.save(csrf,parsed.data as AdminProductInput,initial?.id,initial?.version);setDirty(false);onSaved(p);}catch(e){fail(e);}finally{setBusy(false);}
 }
 async function upload(file:File){
  if(images.length>=12){setError('Use up to 12 images per product');return;}if(file.size>8*1024*1024){setError('Choose an image smaller than 8 MB');return;}
  setUploading(true);setError('');try{const result=await adminApi.upload(csrf,file);change(()=>setImages(old=>[...old,result.url]));}catch(e){fail(e);}finally{setUploading(false);}
 }
 async function createCategory(){
  if(!categoryName.trim()||!categorySlug.trim()){setError('Enter a category name and URL slug');return;}setCategoryBusy(true);setError('');try{const c=await adminApi.category(csrf,categorySlug,categoryName);change(()=>setSelected(old=>[...old,c.slug]));setCategoryName('');setCategorySlug('');onCategories();}catch(e){fail(e);}finally{setCategoryBusy(false);}
 }
 function reorder(index:number,offset:number){change(()=>setImages(old=>{const next=[...old];[next[index],next[index+offset]]=[next[index+offset],next[index]];return next;}));}
 return <form className="admin-editor" onSubmit={e=>{e.preventDefault();save();}}><div className="admin-editor-heading"><div><p className="eyebrow">Catalogue editor</p><h1>{initial?'Edit jewellery':'Add jewellery'}</h1><p className="muted">{initial?`Version ${initial.version} · ${initial.active?'Active':'Draft'}`:'New products start as drafts.'}{dirty?' · Unsaved changes':''}</p></div><div className="admin-actions"><button type="button" className="secondary" onClick={()=>{if(!dirty||window.confirm('Discard your unsaved changes?'))onCancel();}}>Back to products</button>{!readOnly&&<button className="primary" disabled={busy||uploading||categoryBusy}><Save size={17}/>{busy?'Saving…':'Save product'}</button>}</div></div>{error&&<div className="error" role="alert">{error}{(error.includes('changed since')||error.includes('latest version'))&&<button type="button" className="text-button" onClick={()=>{if(window.confirm('Discard these edits and load the latest saved version?'))onCancel();}}>Return to list and reopen</button>}</div>}
 <fieldset disabled={readOnly||busy} className="admin-fieldset"><div className="admin-editor-grid"><div><section className="admin-panel"><h2>Product information</h2><label>Name<input value={name} required maxLength={200} onChange={e=>change(()=>{setName(e.target.value);if(!initial)setSlug(slugify(e.target.value));})}/></label><label>Product URL slug<input value={slug} disabled={!!initial} required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={120} onChange={e=>change(()=>setSlug(e.target.value))}/></label><p className="muted">The URL is fixed after creation to preserve existing links.</p><label>Description<textarea value={description} required maxLength={6000} rows={5} onChange={e=>change(()=>setDescription(e.target.value))}/></label></section>
 <section className="admin-panel"><div className="section-heading"><h2>Product images</h2><span className="muted">{images.length}/12</span></div><p className="muted">The first image is the cover. Upload JPEG, PNG, WebP or AVIF; uploads are optimized to WebP.</p><div className="admin-image-grid">{images.map((src,i)=><div key={src+'-'+i}><img src={src} alt={`Product image ${i+1}`} width="180" height="180"/><div><button type="button" disabled={i===0} aria-label={`Move image ${i+1} earlier`} onClick={()=>reorder(i,-1)}><ArrowUp size={15}/></button><button type="button" disabled={i===images.length-1} aria-label={`Move image ${i+1} later`} onClick={()=>reorder(i,1)}><ArrowDown size={15}/></button><button type="button" aria-label={`Remove image ${i+1}`} onClick={()=>change(()=>setImages(old=>old.filter((_,index)=>index!==i)))}><Trash2 size={15}/></button></div>{i===0&&<span className="muted">Cover image</span>}</div>)}</div><label className="upload-label"><Upload size={17}/>{uploading?'Uploading…':'Upload one image'}<input type="file" disabled={uploading||images.length>=12} accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)upload(file);}}/></label><label>Or use an image URL<input value={url} placeholder="https://images.example.com/product.webp" onChange={e=>setUrl(e.target.value)}/></label><button type="button" className="secondary" disabled={images.length>=12} onClick={()=>{const valid=imageUrlSchema.safeParse(url);if(!valid.success){setError(valid.error.issues[0].message);return;}change(()=>setImages(old=>[...old,valid.data]));setUrl('');}}>Add image URL</button></section>
 <section className="admin-panel"><div className="section-heading"><h2>Variants, prices & stock</h2><button type="button" className="text-button" disabled={variants.length>=20} onClick={()=>change(()=>setVariants(old=>[...old,blankVariant()]))}><Plus size={16}/>Add variant</button></div><p className="muted">Enter prices in rupees. Stock is the available quantity. Removing an existing variant archives it.</p>{variants.map((v,i)=><div className="admin-variant" key={v.id||'new-'+i}><div className="section-heading"><h3>Variant {i+1}</h3><button type="button" className="text-button" disabled={variants.length<=1} onClick={()=>change(()=>setVariants(old=>old.filter((_,index)=>index!==i)))}>Remove variant</button></div><div className="admin-form-grid"><label>SKU<input value={v.sku} required maxLength={80} onChange={e=>updateVariant(i,'sku',e.target.value)}/></label><label>Option label<input value={v.label} required maxLength={100} onChange={e=>updateVariant(i,'label',e.target.value)}/></label><label>Selling price ₹<input type="number" value={v.price} required min="0.01" max="1000000" step="0.01" onChange={e=>updateVariant(i,'price',e.target.value)}/></label><label>Original price ₹ (optional)<input type="number" value={v.original} min="0.01" max="1000000" step="0.01" onChange={e=>updateVariant(i,'original',e.target.value)}/></label><label>Available stock<input type="number" value={v.stock} required min="0" max="1000000" step="1" onChange={e=>updateVariant(i,'stock',e.target.value)}/></label><label>Colour<input value={v.colour} required maxLength={80} onChange={e=>updateVariant(i,'colour',e.target.value)}/></label><label>Material<input value={v.material} required maxLength={100} onChange={e=>updateVariant(i,'material',e.target.value)}/></label><label>Gender<input value={v.gender} required maxLength={80} onChange={e=>updateVariant(i,'gender',e.target.value)}/></label></div></div>)}</section></div>
 <aside><section className="admin-panel"><h2>Visibility</h2><label className="checkbox"><input type="checkbox" checked={active} onChange={e=>change(()=>setActive(e.target.checked))}/>Active in the public catalogue</label><label>Featured order<input type="number" required min="0" max="100000" step="1" value={rank} onChange={e=>change(()=>setRank(e.target.value))}/></label><p className="muted">Lower numbers appear first in featured sorting.</p>{initial?.active&&<a className="text-button" href={'/preview-product/?slug='+encodeURIComponent(initial.slug)} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Preview saved product</a>}<p className="muted">New static product URLs require a Pages rebuild after deployment. Local development resolves products from the API.</p></section><section className="admin-panel"><h2>Categories</h2><div className="admin-categories">{categories.map(c=><label className="checkbox" key={c.slug}><input type="checkbox" checked={selected.includes(c.slug)} onChange={e=>change(()=>setSelected(old=>e.target.checked?[...old,c.slug]:old.filter(s=>s!==c.slug)))}/>{c.name}</label>)}</div><details><summary>Create a category</summary><label>Category name<input value={categoryName} maxLength={80} onChange={e=>{setCategoryName(e.target.value);setCategorySlug(slugify(e.target.value));}}/></label><label>Category slug<input value={categorySlug} maxLength={120} onChange={e=>setCategorySlug(e.target.value)}/></label><button type="button" className="secondary" disabled={categoryBusy} onClick={createCategory}>{categoryBusy?'Creating…':'Create category'}</button></details></section></aside></div></fieldset></form>;
}
