import { useEffect, useState } from 'react';
import { Minus, Plus, Trash2, Heart, ShoppingBag } from 'lucide-react';
import { money, promotions, type Product, type Quote } from '@store/contracts';
import { api } from '../lib/api';
import { setQuantity, toggleWish } from '../lib/basket';
import { mutateBasket, useBasket } from '../lib/useBasket';
export default function Cart(){
  const {basket,ready}=useBasket();const [products,setProducts]=useState<Record<string,Product>>({}),[catalogueError,setCatalogueError]=useState('');
  const [quote,setQuote]=useState<Quote|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const [couponText,setCouponText]=useState(''),[coupon,setCoupon]=useState(''),[giftWrap,setGiftWrap]=useState(false),[delivery,setDelivery]=useState<'standard'|'express'>('standard'),[refresh,setRefresh]=useState(0);
  const cartKey=JSON.stringify(basket.cart);
  useEffect(()=>{if(!ready)return;const c=new AbortController();setCatalogueError('');const slugs=[...new Set(basket.cart.map(l=>l.slug))];Promise.all(slugs.map(s=>api.product(s,c.signal).then(p=>[s,p] as const).catch(err=>{if(c.signal.aborted)throw err;return [s,null] as const;}))).then(entries=>{if(c.signal.aborted)return;const found=entries.filter((e):e is readonly [string,Product]=>e[1]!==null);setProducts(Object.fromEntries(found));if(found.length<slugs.length)setCatalogueError('Some items could not be loaded. Remove unavailable items or retry.');}).catch(()=>{});return()=>c.abort();},[cartKey,ready,refresh]);
  useEffect(()=>{if(!ready||!basket.cart.length){setQuote(null);setError('');setLoading(false);return;}const c=new AbortController();setLoading(true);setError('');setQuote(null);
    api.quote({items:basket.cart.map(({variantId,quantity})=>({variantId,quantity})),coupon,prepaid:false,giftWrap,delivery},c.signal).then(q=>setQuote(q)).catch(e=>{if(!c.signal.aborted)setError(e.message||'Unable to calculate totals');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();
  },[cartKey,ready,coupon,giftWrap,delivery,refresh]);
  useEffect(()=>{if(!quote)return;const t=setTimeout(()=>setRefresh(n=>n+1),Math.max(0,new Date(quote.expiresAt).getTime()-Date.now()));return()=>clearTimeout(t);},[quote]);
  function change(fn:Parameters<typeof mutateBasket>[0]){try{mutateBasket(fn);}catch{setError('Unable to save changes. Please allow browser storage.');}}
  if(!ready)return <section className="page-section"><p role="status">Loading your cart…</p></section>;
  if(!basket.cart.length)return <section className="empty page-section"><ShoppingBag size={38}/><h1>Your cart is waiting</h1><p>Find a little something to make your day shine.</p><a className="primary" href="/shop/">Explore jewellery</a></section>;
  return <section className="page-section"><div className="page-heading"><p className="eyebrow">Your favourites, together</p><h1>Shopping cart</h1><p>Your cart is saved on this device.</p></div><div className="cart-layout"><div><div className="cart-items">{basket.cart.map(line=>{const p=products[line.slug],v=p?.variants.find(v=>v.id===line.variantId);return <article className="cart-line" key={line.variantId}><a href={'/products/'+line.slug+'/'}><img src={p?.images[0]||'/placeholder.svg'} alt={p?.name||'Jewellery product'} width="110" height="130"/></a><div><h2><a href={'/products/'+line.slug+'/'}>{p?.name||'Loading or unavailable item'}</a></h2><p className="muted">{v?.label||line.variantId}</p>{v&&<p className="price">{money(v.pricePaise)}</p>}<div className="line-actions"><div className="quantity"><button aria-label={`Decrease ${p?.name||'item'} quantity`} onClick={()=>change(b=>setQuantity(b,line.variantId,line.quantity-1))}><Minus size={14}/></button><span>{line.quantity}</span><button aria-label={`Increase ${p?.name||'item'} quantity`} disabled={line.quantity>=Math.min(20,v?.stock??20)} onClick={()=>change(b=>setQuantity(b,line.variantId,line.quantity+1))}><Plus size={14}/></button></div><button aria-label={`Remove ${p?.name||'item'}`} onClick={()=>change(b=>setQuantity(b,line.variantId,0))}><Trash2 size={17}/></button><button className="text-button" onClick={()=>change(b=>{const saved=b.wishlist.includes(line.slug)?b:toggleWish(b,line.slug);return setQuantity(saved,line.variantId,0);})}><Heart size={15}/>Save for later</button></div></div>{v&&<strong>{money(v.pricePaise*line.quantity)}</strong>}</article>;})}</div>{catalogueError&&<p className="error" role="alert">{catalogueError}</p>}
      <div className="checkout-options"><h2>Make it yours</h2><label className="checkbox"><input type="checkbox" checked={giftWrap} onChange={e=>setGiftWrap(e.target.checked)}/>Add gift wrapping · {money(promotions.giftWrapPaise)}</label><label>Delivery<select value={delivery} onChange={e=>setDelivery(e.target.value as 'standard'|'express')}><option value="standard">Standard estimate</option><option value="express">Express estimate · extra {money(promotions.expressExtraPaise)}</option></select></label></div><a className="text-button" href="/shop/">Continue shopping</a></div>
      <aside className="order-summary"><h2>Order summary</h2><form onSubmit={e=>{e.preventDefault();setCoupon(couponText.trim().toUpperCase());setRefresh(n=>n+1);}}><label htmlFor="coupon">Offer code</label><div className="inline-form"><input id="coupon" value={couponText} maxLength={30} placeholder="WELCOME10 or FESTIVE225" onChange={e=>setCouponText(e.target.value)}/><button className="secondary">Apply</button></div></form>{coupon&&<button className="text-button" onClick={()=>{setCoupon('');setCouponText('');}}>Remove {coupon}</button>}{loading&&<p role="status">Calculating current totals…</p>}{error&&<div className="error" role="alert"><p>{error}</p><button className="text-button" onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>}{quote&&!loading&&<><dl className="totals"><dt>Items</dt><dd>{money(quote.subtotalPaise)}</dd>{quote.couponDiscountPaise>0&&<><dt>Offer discount</dt><dd>−{money(quote.couponDiscountPaise)}</dd></>}{quote.prepaidDiscountPaise>0&&<><dt>Prepaid savings</dt><dd>−{money(quote.prepaidDiscountPaise)}</dd></>}<dt>Shipping estimate</dt><dd>{quote.shippingPaise?money(quote.shippingPaise):'Free'}</dd>{quote.giftWrapPaise>0&&<><dt>Gift wrapping</dt><dd>{money(quote.giftWrapPaise)}</dd></>}<dt className="total">Estimated total</dt><dd className="total">{money(quote.totalPaise)}</dd></dl><a className="primary full" href="/checkout/">Continue to checkout</a><div className="quote-notices">{quote.notices.map(n=><p key={n}>{n}</p>)}</div></>}<p className="muted">Free standard shipping estimate from {money(promotions.freeShippingThresholdPaise)} merchandise value.</p></aside></div></section>;
}
