import { useEffect, useState } from 'react';
import { SlidersHorizontal, X } from 'lucide-react';
import type { z } from 'zod';
import { facetsSchema, type Product } from '@store/contracts';
import { api } from '../lib/api';
import ProductCard from './ProductCard';
type Facets=z.infer<typeof facetsSchema>;
const keys=['q','category','colour','material','gender','minPrice','maxPrice','sort','page'] as const;
function cleanParams(raw:URLSearchParams){const q=new URLSearchParams();for(const key of keys){const value=raw.get(key);if(value)q.set(key,value);}return q;}
export default function Catalogue({initial,facets}:{initial:Product[],facets:Facets}){
  const [items,setItems]=useState(initial.slice(0,12));const [total,setTotal]=useState(initial.length);
  const [params,setParams]=useState(new URLSearchParams());const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [filterOpen,setFilterOpen]=useState(false);const [refresh,setRefresh]=useState(0);
  const [priceMin,setPriceMin]=useState('');const [priceMax,setPriceMax]=useState('');
  const key=params.toString();
  useEffect(()=>{const sync=()=>setParams(cleanParams(new URLSearchParams(window.location.search)));sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
  useEffect(()=>{setPriceMin(params.has('minPrice')?String(Number(params.get('minPrice'))/100):'');setPriceMax(params.has('maxPrice')?String(Number(params.get('maxPrice'))/100):'');},[key]);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');api.products(params,controller.signal).then(data=>{setItems(data.items);setTotal(data.total);}).catch(err=>{if(!controller.signal.aborted)setError(err.message||'Unable to load products');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[key,refresh]);
  function change(values:Record<string,string>){const next=new URLSearchParams(params);for(const [k,v] of Object.entries(values)){if(v)next.set(k,v);else next.delete(k);}if(!('page' in values))next.delete('page');setParams(next);window.history.pushState({},'',window.location.pathname+(next.size?'?'+next:''));}
  const select=(label:string,key:string,options:{value:string,label:string}[])=> <details open><summary>{label}</summary><label className="sr-only" htmlFor={'filter-'+key}>{label}</label><select id={'filter-'+key} value={params.get(key)||''} onChange={e=>change({[key]:e.target.value})}><option value="">All {label.toLowerCase()}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></details>;
  const page=Number(params.get('page')||1);const pages=Math.ceil(total/12);
  return <section className="catalogue" id="catalogue" aria-label="Jewellery catalogue"><div className="catalogue-top"><button className="filter-toggle" onClick={()=>setFilterOpen(!filterOpen)} aria-expanded={filterOpen} aria-controls="catalogue-filters"><SlidersHorizontal size={17}/>Filter</button><p>{loading?'Updating…':`${total} products`}</p><label>Sort <select value={params.get('sort')||'featured'} onChange={e=>change({sort:e.target.value})}><option value="featured">Featured</option><option value="name">Alphabetically, A–Z</option><option value="price-asc">Price, low to high</option><option value="price-desc">Price, high to low</option></select></label></div>
    <div className="catalogue-layout"><aside id="catalogue-filters" className={'filters '+(filterOpen?'is-open':'')}><div className="filter-heading"><h2>Filter</h2><button className="filter-close" aria-label="Close filters" onClick={()=>setFilterOpen(false)}><X size={20}/></button></div><details open><summary>Price</summary><form className="price-filter" onSubmit={e=>{e.preventDefault();const min=priceMin.trim()===''?'':Math.round(Number(priceMin)*100),max=priceMax.trim()===''?'':Math.round(Number(priceMax)*100);if(min!==''&&max!==''&&min>max){setError('Minimum price must not exceed maximum price');return;}change({minPrice:String(min),maxPrice:String(max)});}}><label>Min ₹<input type="number" min="0" max="1000000" step="0.01" value={priceMin} onChange={e=>setPriceMin(e.target.value)}/></label><label>Max ₹<input type="number" min="0" max="1000000" step="0.01" value={priceMax} onChange={e=>setPriceMax(e.target.value)}/></label><button className="text-button">Apply price</button></form></details>
      {select('Product Category','category',facets.categories.map(c=>({value:c.slug,label:c.name})))}{select('Colour','colour',facets.colours.map(value=>({value,label:value})))}{select('Material','material',facets.materials.map(value=>({value,label:value})))}{select('Gender','gender',facets.genders.map(value=>({value,label:value})))}<button className="text-button" onClick={()=>{change(Object.fromEntries(keys.map(k=>[k,''])));setPriceMin('');setPriceMax('');}}>Clear filters</button></aside>
      <div className="results" aria-busy={loading}>{params.get('q')&&<p>Results for “{params.get('q')}”</p>}{error?<div className="error" role="alert">{error}<button className="text-button" onClick={()=>setRefresh(n=>n+1)}>Try again</button></div>:<><div className="product-grid">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!items.length&&!loading&&<div className="empty"><h2>No jewellery found</h2><p>Try a different search or clear your filters.</p></div>}</>}{pages>1&&!error&&<nav className="pagination" aria-label="Product pages"><button disabled={page<=1||loading} onClick={()=>change({page:String(page-1)})}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages||loading} onClick={()=>change({page:String(page+1)})}>Next</button></nav>}</div></div></section>;
}
