import { useEffect, useState } from 'react';
import { Heart, ShoppingBag } from 'lucide-react';
import { money, type Product } from '@store/contracts';
import { api } from '../lib/api';
import { addLine, toggleWish } from '../lib/basket';
import { mutateBasket, useBasket } from '../lib/useBasket';
export default function ProductDetail({initial}:{initial:Product}){
  const [p,setProduct]=useState(initial),[index,setIndex]=useState(0),[quantity,setQuantity]=useState(1),[image,setImage]=useState(0),[status,setStatus]=useState(''),[error,setError]=useState(''),[live,setLive]=useState(false);
  const {basket}=useBasket();const v=p.variants[index]||p.variants[0];const saved=basket.wishlist.includes(p.slug);
  useEffect(()=>{const c=new AbortController();api.product(initial.slug,c.signal).then(value=>{setProduct(value);setLive(true);}).catch(e=>{if(!c.signal.aborted)setError(e.message||'Unable to verify availability');});return()=>c.abort();},[initial.slug]);
  function add(checkout=false){try{mutateBasket(b=>addLine(b,{variantId:v.id,slug:p.slug,quantity}));setStatus('Added to your cart');if(checkout)window.location.href='/checkout/';}catch{setError('Unable to save your cart. Please allow browser storage.');}}
  return <section className="product-detail"><div className="detail-gallery"><img className="detail-main" src={p.images[image]||'/placeholder.svg'} alt={p.name} width="700" height="800"/><div className="thumbnails">{p.images.map((src,i)=><button key={src} className={image===i?'selected':''} aria-label={`View image ${i+1}`} aria-pressed={image===i} onClick={()=>setImage(i)}><img src={src} alt="" width="90" height="100"/></button>)}</div></div><div className="detail-info"><p className="eyebrow">A little everyday sparkle</p><h1>{p.name}</h1><div className="price large">{money(v.pricePaise)}{v.compareAtPaise&&v.compareAtPaise>v.pricePaise&&<del>{money(v.compareAtPaise)}</del>}</div><p>{p.description}</p>{p.variants.length>1&&<label>Choose an option<select value={v.id} onChange={e=>{setIndex(p.variants.findIndex(v=>v.id===e.target.value));setQuantity(1);}}>{p.variants.map(v=><option key={v.id} value={v.id}>{v.label} · {money(v.pricePaise)}</option>)}</select></label>}<p className="stock">{live?(v.stock?`${v.stock} available`:'Currently sold out'):'Checking current availability…'}</p><div className="buy-row"><label>Quantity<input aria-label="Quantity" type="number" min="1" max={Math.max(1,Math.min(20,v.stock))} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(20,v.stock||1,Number(e.target.value)||1)))}/></label><button className="primary" disabled={!live||!v.stock} onClick={()=>add()}><ShoppingBag size={18}/>Add to cart</button><button className="icon-button" aria-label={saved?'Remove from wishlist':'Save to wishlist'} aria-pressed={saved} onClick={()=>{try{mutateBasket(b=>toggleWish(b,p.slug));setStatus(saved?'Removed from wishlist':'Saved to wishlist');}catch{setError('Unable to save wishlist');}}}><Heart size={20} fill={saved?'currentColor':'none'}/></button></div><button className="secondary full" disabled={!live||!v.stock} onClick={()=>add(true)}>Continue to checkout</button>{error&&<p className="error" role="alert">{error}</p>}<p role="status">{status}</p><details open><summary>Product details</summary><dl className="specs"><dt>SKU</dt><dd>{v.sku}</dd><dt>Colour</dt><dd>{v.colour}</dd><dt>Material</dt><dd>{v.material}</dd></dl></details><details><summary>Jewellery care</summary><p>Store separately in a dry pouch. Follow the care instructions supplied with your jewellery.</p></details><details><summary>Delivery & returns</summary><p>See our <a href="/help/#delivery">delivery information</a>. Live shipping and returns policies will be added before launch.</p></details></div></section>;
}
