import { useEffect,useState } from 'react';
import { z } from 'zod';
import { returnRecordSchema,money,type OrderReceipt,type ReturnRecord } from '@store/contracts';
import { request } from '../lib/api';
import { customerRead,customerWrite } from '../lib/customer-api';
export type OrderAccess={id:string,secret:string}|{csrf:string};
export default function ReturnPanel({order,auth}:{order:OrderReceipt,auth:OrderAccess}){
 const [items,setItems]=useState<ReturnRecord[]>([]),[reason,setReason]=useState(''),[kind,setKind]=useState<'cancel'|'return'>(order.status==='delivered'?'return':'cancel'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
 const schema=z.array(returnRecordSchema),account='csrf' in auth;
 async function load(){const rows=account?await customerRead('/orders/'+order.id+'/returns',schema):await request('/api/v1/orders/returns',schema,{method:'POST',body:JSON.stringify(auth),cache:'no-store'});setItems(rows);}
 useEffect(()=>{let active=true;setReady(false);setError('');const promise=account?customerRead('/orders/'+order.id+'/returns',schema):request('/api/v1/orders/returns',schema,{method:'POST',body:JSON.stringify(auth),cache:'no-store'});promise.then(rows=>{if(active)setItems(rows);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[order.id,order.status,order.paymentStatus]);
 async function submit(){setBusy(true);setError('');try{const body={orderId:order.id,requestKey:crypto.randomUUID(),kind,reason};if(account)await customerWrite('/returns',returnRecordSchema,body,auth.csrf);else await request('/api/v1/returns',returnRecordSchema,{method:'POST',body:JSON.stringify({...body,secret:auth.secret})});await load();setReason('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{setKind(order.status==='delivered'?'return':'cancel');},[order.status]);
 const eligible=order.paymentStatus!=='refunded'&&(order.status==='delivered'||(['pending','confirmed','cancelled'].includes(order.status)&&(order.paymentMethod==='cod'||['paid','review'].includes(order.paymentStatus))));
 return <section className="return-panel"><h3>Returns & cancellation</h3><p className="muted">Requests cover the full order. The store reviews eligibility before a refund or stock return. Return requests are available after delivery within the configured return window.</p>{error&&<p className="error" role="alert">{error}</p>}{!ready&&<p role="status">Loading requests…</p>}{items.map(r=><article className="return-card" key={r.id}><strong>{r.kind==='return'?'Return':'Cancellation'} · {r.state.replaceAll('_',' ')}</strong><p>{r.reason}</p>{r.response&&<p>Store response: {r.response}</p>}<p>Refund amount: {money(r.amountPaise)} · {r.refundState}</p><ol className="order-timeline">{r.events.map(e=><li key={e.id}>{e.note}<time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString()}</time></li>)}</ol></article>)}{ready&&!items.some(r=>r.state!=='rejected')&&eligible&&<form className="return-form" onSubmit={e=>{e.preventDefault();void submit();}}><label>Request type<select value={kind} onChange={e=>setKind(e.target.value as 'cancel'|'return')}><option value={order.status==='delivered'?'return':'cancel'}>{order.status==='delivered'?'Return full order':'Cancel before dispatch'}</option></select></label><label>Reason<textarea required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tell us why you are requesting this. Do not include bank or card details."/></label><button className="secondary" disabled={busy}>{busy?'Submitting…':'Submit request'}</button></form>}{ready&&!eligible&&!items.length&&<p className="muted">A new request is unavailable at this order stage. Unpaid online orders should be checked through payment status first.</p>}<button className="text-button" disabled={busy} onClick={()=>{setBusy(true);setError('');load().catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Refresh requests</button></section>;
}
