import { randomUUID } from 'node:crypto';
import { and,asc,desc,eq,inArray,sql } from 'drizzle-orm';
import type { z } from 'zod';
import { adminReturnRecordSchema,returnRequestSchema,returnReviewSchema } from '@store/contracts';
import * as s from './schema.js';
import { CommerceError } from './quote.js';
import type { CommerceDb,CommerceTx } from './email.js';
import type { OrderRepository } from './orders.js';
import type { PaymentGateway,GatewayRefund } from './razorpay.js';
export function returnService(db:CommerceDb,orders:OrderRepository,gateway?:PaymentGateway,windowDays=14){
 const fail=(message:string)=>{throw new CommerceError(409,'RETURN_CONFLICT',message);};
 async function record(tx:CommerceTx,id:string,state:string,note:string,userId:string|null=null){await tx.insert(s.returnEvents).values({id:randomUUID(),requestId:id,state,note,userId});}
 async function detail(id:string){const row=(await db.select({r:s.returnRequests,o:s.orders}).from(s.returnRequests).innerJoin(s.orders,eq(s.orders.id,s.returnRequests.orderId)).where(eq(s.returnRequests.id,id)))[0];if(!row)throw new CommerceError(404,'NOT_FOUND','Return request not found');const events=await db.select({id:s.returnEvents.id,state:s.returnEvents.state,note:s.returnEvents.note,createdAt:s.returnEvents.createdAt}).from(s.returnEvents).where(eq(s.returnEvents.requestId,id)).orderBy(asc(s.returnEvents.createdAt),asc(s.returnEvents.id));return adminReturnRecordSchema.parse({...row.r,number:row.o.number,mode:row.o.mode,createdAt:row.r.createdAt.toISOString(),updatedAt:row.r.updatedAt.toISOString(),events:events.map(e=>({...e,createdAt:e.createdAt.toISOString()}))});}
 async function locked(tx:CommerceTx,id:string){const ref=(await tx.select({orderId:s.returnRequests.orderId}).from(s.returnRequests).where(eq(s.returnRequests.id,id)))[0];if(!ref)throw new CommerceError(404,'NOT_FOUND','Return request not found');const order=(await tx.select().from(s.orders).where(eq(s.orders.id,ref.orderId)).for('update'))[0];const row=(await tx.select().from(s.returnRequests).where(eq(s.returnRequests.id,id)).for('update'))[0];return {row,order};}
 async function restock(tx:CommerceTx,row:typeof s.returnRequests.$inferSelect,order:typeof s.orders.$inferSelect,userId:string|null){if(row.restocked)return;if(!order.inventoryReleased){const lines=await tx.select().from(s.orderLines).where(eq(s.orderLines.orderId,order.id));await tx.select().from(s.products).where(inArray(s.products.id,[...new Set(lines.map(l=>l.productId))].sort())).orderBy(asc(s.products.id)).for('update');const stock=await tx.select().from(s.inventory).where(inArray(s.inventory.variantId,lines.map(l=>l.variantId))).orderBy(asc(s.inventory.variantId)).for('update');for(const line of lines){const before=stock.find(i=>i.variantId===line.variantId)?.available;if(before===undefined||before+line.quantity>1000000)fail('Resolve inventory before restocking');await tx.update(s.inventory).set({available:before!+line.quantity,updatedAt:new Date()}).where(eq(s.inventory.variantId,line.variantId));await tx.insert(s.inventoryMovements).values({id:randomUUID(),variantId:line.variantId,orderId:order.id,userId,beforeQuantity:before!,afterQuantity:before!+line.quantity,reason:'Approved return/cancellation restocked'});}await tx.update(s.products).set({version:sql`${s.products.version}+1`,updatedAt:new Date()}).where(inArray(s.products.id,[...new Set(lines.map(l=>l.productId))]));await tx.update(s.orders).set({inventoryReleased:true,version:sql`${s.orders.version}+1`,updatedAt:new Date()}).where(eq(s.orders.id,order.id));}
  await tx.update(s.returnRequests).set({restocked:true}).where(eq(s.returnRequests.id,row.id));
 }
 async function applyRefund(id:string,remote:GatewayRefund,adopt=false){
  await db.transaction(async tx=>{const {row,order}=await locked(tx,id);if(!row.paymentId||row.gatewayKeyId!==gateway?.keyId||remote.payment_id!==row.paymentId||remote.amount!==row.amountPaise||remote.currency!=='INR'||(row.refundId&&row.refundId!==remote.id)||(!adopt&&remote.receipt!==row.id&&(!remote.notes||Array.isArray(remote.notes)||remote.notes.local_return_id!==row.id)))fail('Provider refund does not match this request');
   if(row.state==='refunded'||row.state==='closed')return;
   if(!['creating','uncertain','pending','failed'].includes(row.refundState))fail('This request has no initiated refund');
   if(remote.status==='processed'){
    await tx.update(s.returnRequests).set({refundId:remote.id,refundState:'processed',state:'refunded',refundIssue:null,version:sql`${s.returnRequests.version}+1`,updatedAt:new Date()}).where(eq(s.returnRequests.id,id));const status=row.kind==='cancel'?'cancelled':order.status;await tx.update(s.orders).set({paymentStatus:'refunded',status,version:sql`${s.orders.version}+1`,updatedAt:new Date()}).where(eq(s.orders.id,order.id));await tx.insert(s.orderEvents).values({id:randomUUID(),orderId:order.id,userId:null,status,paymentStatus:'refunded',note:'Processed provider refund verified'});await record(tx,id,'refunded','Full online refund verified as processed');
   }else{const state=remote.status==='failed'?'failed':'pending';await tx.update(s.returnRequests).set({refundId:remote.id,refundState:state,refundIssue:state==='failed'?'Provider refund failed; review before any new refund':null,version:row.refundId===remote.id&&row.refundState===state?row.version:row.version+1,updatedAt:new Date()}).where(eq(s.returnRequests.id,id));}
  });
 }
 async function check(id:string){const row=(await db.select().from(s.returnRequests).where(eq(s.returnRequests.id,id)))[0];if(!row)throw new CommerceError(404,'NOT_FOUND','Return request not found');if(['refunded','closed'].includes(row.state))return detail(id);if(!gateway?.refunds||!gateway.refund||row.gatewayKeyId!==gateway.keyId||!row.paymentId)fail('Use the original configured test gateway to reconcile');
  if(row.refundId)await applyRefund(id,await gateway!.refund!(row.refundId));else{const matches=(await gateway!.refunds!(row.paymentId!)).filter(r=>r.receipt===id||(!Array.isArray(r.notes)&&r.notes?.local_return_id===id));if(matches.length>1)fail('Multiple provider refunds require review');if(matches[0])await applyRefund(id,matches[0]);else if(Date.now()-row.updatedAt.getTime()>30000)await db.update(s.returnRequests).set({refundState:'uncertain',refundIssue:'No matching provider refund found; review the original request before any further refund',updatedAt:new Date()}).where(eq(s.returnRequests.id,id));}
  return detail(id);
 }
 async function refund(id:string,userId:string,version:number){
  if(!gateway?.refundCreate||!/^rzp_test_/.test(gateway.keyId))throw new CommerceError(503,'REFUND_DISABLED','Online refunds require the configured Razorpay test gateway');
  const snapshot=(await db.select().from(s.returnRequests).where(eq(s.returnRequests.id,id)))[0];if(!snapshot)throw new CommerceError(404,'NOT_FOUND','Return request not found');
  if(snapshot.refundState!=='none')return check(id);
  const order=(await db.select().from(s.orders).where(eq(s.orders.id,snapshot.orderId)))[0],session=(await db.select().from(s.paymentSessions).where(eq(s.paymentSessions.orderId,snapshot.orderId)))[0];if(order.mode!=='test'||order.paymentMethod!=='online'||!session?.paymentId||session.keyId!==gateway.keyId)fail('This order has no verified test payment');
  const payment=await gateway.payment(session!.paymentId!);if(payment.id!==session!.paymentId||payment.order_id!==session!.gatewayOrderId||payment.amount!==order.totalPaise||payment.currency!=='INR'||payment.status!=='captured'||!payment.captured||payment.amount_refunded!==0)fail('Check provider payment/refunds before requesting a full refund');
  const claimed=await db.transaction(async tx=>{const {row,order:current}=await locked(tx,id);if(row.refundState!=='none')return false;if(row.version!==version)fail('Request changed; reload before refunding');if(current.paymentStatus!=='paid'&&current.paymentStatus!=='review')fail('The payment is not refundable');if((row.kind==='cancel'&&!['pending','confirmed','cancelled'].includes(current.status))||(row.kind==='return'&&current.status!=='delivered'))fail('Order fulfilment changed; review this request');if((row.kind==='cancel'&&row.state!=='approved')||(row.kind==='return'&&row.state!=='received'))fail('Approve cancellation or receive returned items first');await tx.update(s.returnRequests).set({state:'refund_pending',refundState:'creating',gatewayKeyId:gateway.keyId,paymentId:payment.id,version:row.version+1,updatedAt:new Date()}).where(eq(s.returnRequests.id,id));await tx.update(s.orders).set({paymentStatus:'review',version:sql`${s.orders.version}+1`,updatedAt:new Date()}).where(eq(s.orders.id,row.orderId));await record(tx,id,'refund_pending','Online test refund requested',userId);return true;});
  if(!claimed)return check(id);
  try{await applyRefund(id,await gateway.refundCreate!(payment.id,snapshot.amountPaise,id));}catch(error){await db.update(s.returnRequests).set({refundState:'uncertain',refundIssue:'Refund response uncertain; check provider before retrying'}).where(and(eq(s.returnRequests.id,id),sql`${s.returnRequests.refundId} IS NULL`));throw error;}return detail(id);
 }
 return {detail,check,
  async create(input:z.infer<typeof returnRequestSchema>,customerId:string|null){const id=await db.transaction(async tx=>{const order=(await tx.select().from(s.orders).where(eq(s.orders.id,input.orderId)).for('update'))[0];if(!order)throw new CommerceError(404,'NOT_FOUND','Order not found');const previous=(await tx.select().from(s.returnRequests).where(eq(s.returnRequests.requestKey,input.requestKey)))[0];if(previous){if(previous.orderId!==input.orderId||previous.kind!==input.kind||previous.reason!==input.reason)fail('Request key belongs to another submission');return previous.id;}
   const active=(await tx.select().from(s.returnRequests).where(and(eq(s.returnRequests.orderId,input.orderId),sql`${s.returnRequests.state}<>'rejected'`)))[0];if(active){if(active.kind===input.kind&&active.reason===input.reason)return active.id;fail('An existing return/refund request already covers this order');}
   if(order.paymentStatus==='refunded')fail('This order has already been refunded');
   if(input.kind==='cancel'){if(!['pending','confirmed','cancelled'].includes(order.status))fail('Dispatched orders cannot use pre-dispatch cancellation');if(order.status==='cancelled'&&order.paymentStatus!=='review')fail('This order is already cancelled');if(order.paymentMethod==='online'&&!['paid','review'].includes(order.paymentStatus))fail('Check payment status first; unpaid online reservations expire through payment reconciliation');}
   else{if(order.status!=='delivered')fail('Return requests are available after delivery');const delivered=(await tx.select().from(s.orderEvents).where(and(eq(s.orderEvents.orderId,order.id),eq(s.orderEvents.status,'delivered'))).orderBy(asc(s.orderEvents.createdAt)).limit(1))[0];if(!delivered||Date.now()-delivered.createdAt.getTime()>windowDays*86400000)fail('The configured return window has ended');}
   const id=randomUUID();await tx.insert(s.returnRequests).values({id,orderId:order.id,requestKey:input.requestKey,customerId,kind:input.kind,reason:input.reason,amountPaise:['paid','review','collected'].includes(order.paymentStatus)?order.totalPaise:0});await record(tx,id,'requested','Request received');return id;});return detail(id);},
  async orderRequests(orderId:string){const rows=await db.select({id:s.returnRequests.id}).from(s.returnRequests).where(eq(s.returnRequests.orderId,orderId)).orderBy(desc(s.returnRequests.createdAt));return Promise.all(rows.map(r=>detail(r.id)));},
  async list(){const rows=await db.select({id:s.returnRequests.id}).from(s.returnRequests).orderBy(desc(s.returnRequests.updatedAt)).limit(100);return Promise.all(rows.map(r=>detail(r.id)));},
  async review(id:string,input:z.infer<typeof returnReviewSchema>,userId:string){
   if(input.action==='check')return check(id);
   if(input.action==='refund')return refund(id,userId,input.version);
   if(input.action==='adopt-refund'){
    const r=(await db.select().from(s.returnRequests).where(eq(s.returnRequests.id,id)))[0];if(!r||!/^rfnd_[A-Za-z0-9]+$/.test(input.reference)||!gateway?.refund)fail('Enter a valid provider refund ID');
    const session=(await db.select().from(s.paymentSessions).where(eq(s.paymentSessions.orderId,r.orderId)))[0];const order=(await db.select().from(s.orders).where(eq(s.orders.id,r.orderId)))[0];if(order.mode!=='test'||order.paymentMethod!=='online'||session?.keyId!==gateway!.keyId||!session?.paymentId)fail('Use the original test payment account');
    const remote=await gateway!.refund!(input.reference),payment=await gateway!.payment(session!.paymentId!);if(remote.id!==input.reference||remote.status!=='processed'||remote.payment_id!==session!.paymentId||remote.amount!==r.amountPaise||remote.currency!=='INR'||payment.id!==session!.paymentId||payment.order_id!==session!.gatewayOrderId||payment.amount!==order.totalPaise||payment.currency!=='INR'||payment.amount_refunded<r.amountPaise)fail('Only a matching fully processed refund can be linked');
    await db.transaction(async tx=>{const {row,order}=await locked(tx,id);if(row.version!==input.version)fail('Reload the changed request');if((row.kind==='cancel'&&!['approved','refund_pending'].includes(row.state))||(row.kind==='return'&&!['received','refund_pending'].includes(row.state)))fail('Approve or receive the request first');if(row.kind==='cancel'&&!['pending','confirmed','cancelled'].includes(order.status))fail('Order was dispatched');if(row.refundId&&row.refundId!==remote.id&&row.refundState!=='failed')fail('Existing refund must be reconciled first');await tx.update(s.returnRequests).set({gatewayKeyId:gateway!.keyId,paymentId:payment.id,refundId:row.refundState==='failed'?null:row.refundId,refundState:'pending'}).where(eq(s.returnRequests.id,id));await record(tx,id,'refund_pending','Admin linked an existing provider refund for verification',userId);});await applyRefund(id,remote,true);return detail(id);
   }
   await db.transaction(async tx=>{const {row,order}=await locked(tx,id);if(row.version!==input.version)fail('Request changed; reload before updating');let state=row.state;
    switch(input.action){
     case 'approve':if(row.state!=='requested')fail('Only requested cases can be approved');if(row.kind==='cancel'&&!['pending','confirmed','cancelled'].includes(order.status))fail('Order was dispatched; review instead');state='approved';break;
     case 'reject':if(row.state!=='requested'||input.response.length<5)fail('Only requested cases can be rejected; provide a reason');state='rejected';break;
     case 'receive':if(row.kind!=='return'||row.state!=='approved')fail('Approve a return before receiving it');state='received';break;
     case 'restock':if(row.restocked)fail('Stock already restored');if(row.kind==='cancel'&&!['approved','refunded','closed'].includes(row.state))fail('Approve cancellation first');if(row.kind==='return'&&!['received','refund_pending','refunded','closed'].includes(row.state))fail('Receive and inspect all returned items first');if(row.kind==='cancel'&&!['pending','confirmed','cancelled'].includes(order.status))fail('Order was dispatched');await restock(tx,row,order,userId);break;
     case 'manual-refund':if(order.paymentMethod!=='cod'||order.paymentStatus!=='collected'||row.amountPaise!==order.totalPaise||input.reference.length<5)fail('Manually refund only collected COD payments, with a payment reference');if((row.kind==='return'&&row.state!=='received')||(row.kind==='cancel'&&row.state!=='approved'))fail('Approve/receive this request first');await tx.update(s.returnRequests).set({refundState:'manual',manualReference:input.reference}).where(eq(s.returnRequests.id,id));await tx.update(s.orders).set({paymentStatus:'refunded',status:row.kind==='cancel'?'cancelled':order.status,version:sql`${s.orders.version}+1`,updatedAt:new Date()}).where(eq(s.orders.id,order.id));await tx.insert(s.orderEvents).values({id:randomUUID(),orderId:order.id,userId,status:row.kind==='cancel'?'cancelled':order.status,paymentStatus:'refunded',note:'Admin confirmed external COD refund'});state='refunded';break;
     case 'close':if(row.amountPaise>0&&row.state!=='refunded')fail('Verify refund completion before closing');if(row.amountPaise===0&&!['approved','received'].includes(row.state))fail('Approve/receive this request first');if(row.kind==='cancel'){if(!['pending','confirmed','cancelled'].includes(order.status))fail('Order was dispatched');await restock(tx,row,order,userId);await tx.update(s.orders).set({status:'cancelled',version:sql`${s.orders.version}+1`,updatedAt:new Date()}).where(eq(s.orders.id,order.id));if(order.status!=='cancelled')await tx.insert(s.orderEvents).values({id:randomUUID(),orderId:order.id,userId,status:'cancelled',paymentStatus:order.paymentStatus,note:'Approved cancellation completed'});}state='closed';break;
     default:fail('Unsupported action');
    }
    await tx.update(s.returnRequests).set({state,response:input.response||row.response,version:row.version+1,updatedAt:new Date()}).where(eq(s.returnRequests.id,id));await record(tx,id,state,input.response||({approve:'Request approved',reject:'Request rejected',receive:'Returned items received',restock:'All items inspected and restocked',close:'Request completed','manual-refund':'External COD refund confirmed'} as Record<string,string>)[input.action],userId);
   });return detail(id);
  },
  async tick(){const rows=await db.select({id:s.returnRequests.id}).from(s.returnRequests).where(eq(s.returnRequests.state,'refund_pending')).orderBy(asc(s.returnRequests.updatedAt)).limit(10);for(const r of rows)try{await check(r.id);}catch{await db.update(s.returnRequests).set({refundIssue:'Provider refund check failed; review and reconcile',updatedAt:new Date()}).where(eq(s.returnRequests.id,r.id));}},
 };
}
export type ReturnService=ReturnType<typeof returnService>;
