import { before,after,beforeEach,test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,randomBytes,createHmac } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { eq } from 'drizzle-orm';
import { emailService,type CommerceDb } from '../src/email.js';
import { customerService } from '../src/customers.js';
import { returnService } from '../src/returns.js';
import { paymentService } from '../src/payments.js';
import type { PaymentGateway,GatewayOrder,GatewayPayment,GatewayRefund } from '../src/razorpay.js';
import { migrateTestDb } from '../../../scripts/migrate-test-db.js';
import { createApp } from '../src/app.js';
import { catalogueRepository } from '../src/catalogue.js';
import { orderRepository } from '../src/orders.js';
import { adminRepository } from '../src/admin-repository.js';
import { mediaStore } from '../src/media.js';
import { seedData } from '../src/seed-data.js';
import { hashPassword } from '../src/password.js';
import * as s from '../src/schema.js';
const pg=new PGlite(),db=drizzle(pg,{schema:s}) as unknown as CommerceDb,origin='http://localhost:4321';
const mail=emailService(db,{driver:'local',siteUrl:origin,encryptionKey:'a'.repeat(64),from:'store@example.test',production:false}),orders=orderRepository(db,{mode:'test',pinPrefixes:[],onlineEnabled:true});
const remotes=new Map<string,GatewayOrder>(),payments=new Map<string,GatewayPayment>(),refunds=new Map<string,GatewayRefund>();let posts=0,uncertain=false,pending=false;
const gateway:PaymentGateway={keyId:'rzp_test_Accounts',keySecret:'test-key-secret',webhookSecrets:['test-webhook-secret-123'],create:async(receipt,amount)=>{const row={id:'order_'+receipt.replaceAll('-',''),receipt,amount,currency:'INR',notes:{local_order_id:receipt},status:'created'};remotes.set(row.id,row);return row;},find:async receipt=>[...remotes.values()].filter(o=>o.receipt===receipt),order:async id=>remotes.get(id)!,payment:async id=>payments.get(id)!,payments:async id=>[...payments.values()].filter(p=>p.order_id===id),refundCreate:async(paymentId,amount,requestId)=>{posts++;const r={id:'rfnd_'+requestId.replaceAll('-',''),payment_id:paymentId,amount,currency:'INR',status:pending?'pending':'processed',receipt:requestId,notes:{local_return_id:requestId}};refunds.set(r.id,r);if(r.status==='processed')payments.get(paymentId)!.amount_refunded=amount;if(uncertain)throw Error('lost response');return r;},refunds:async id=>[...refunds.values()].filter(r=>r.payment_id===id),refund:async id=>refunds.get(id)!};
const customers=customerService(db,mail,orders),returns=returnService(db,orders,gateway),settlements=paymentService(db,orders,gateway);
let app:Awaited<ReturnType<typeof createApp>>,admin:{cookie:string,csrf:string};
const req=(method:'GET'|'POST'|'PUT',url:string,body?:unknown,auth?:{cookie:string,csrf?:string})=>app.inject({method,url,payload:body===undefined?undefined:JSON.stringify(body),headers:{origin,...(body===undefined?{}:{'content-type':'application/json'}),...(auth?{cookie:auth.cookie,...(auth.csrf?{'x-csrf-token':auth.csrf}:{})}:{})}});
async function place(email='customer@example.test',online=false){const body={expectedMode:'test',checkoutKey:randomUUID(),receiptSecret:randomBytes(32).toString('hex'),items:[{variantId:'variant-1',quantity:1}],coupon:'',giftWrap:false,delivery:'standard',paymentMethod:online?'online':'cod',customer:{name:'Customer',email,phone:'9876543210'},address:{line1:'123 Testing Street',line2:'',city:'Bengaluru',state:'Karnataka',postalCode:'560001',country:'IN'},expectedTotalPaise:online?83805:87800};const r=await req('POST','/api/v1/orders',body);assert.equal(r.statusCode,201,r.body);const proof={id:r.json().id,secret:body.receiptSecret};if(online){const start=await req('POST','/api/v1/payments/start',proof),sid=start.json().gatewayOrderId,pid='pay_'+proof.id.replaceAll('-','');payments.set(pid,{id:pid,order_id:sid,amount:83805,currency:'INR',status:'captured',captured:true,amount_refunded:0});remotes.get(sid)!.status='paid';assert.equal((await req('POST','/api/v1/payments/verify',{...proof,razorpay_order_id:sid,razorpay_payment_id:pid,razorpay_signature:createHmac('sha256',gateway.keySecret).update(sid+'|'+pid).digest('hex')})).statusCode,200);}return proof;}
async function token(email:string,purpose='verify'){const entry=(await mail.list()).find(m=>m.recipient===email&&m.subject===(purpose==='verify'?'Verify your email':'Reset your password'));assert.ok(entry);const match=(await mail.preview(entry.id)).text.match(new RegExp('#'+purpose+'=([a-f0-9]{64})'));assert.ok(match);return match[1];}
async function account(email='customer@example.test',verify=true){assert.equal((await req('POST','/api/v1/account/register',{email,name:'Customer',password:'Account-password-12345'})).statusCode,200);if(verify)assert.equal((await req('POST','/api/v1/account/verify',{token:await token(email)})).statusCode,200);const r=await req('POST','/api/v1/account/login',{email,password:'Account-password-12345'});assert.equal(r.statusCode,200,r.body);return {cookie:String(r.headers['set-cookie']).split(';')[0],csrf:r.json().csrfToken,id:r.json().user.id};}
async function requestReturn(proof:{id:string,secret:string},kind='cancel'){const r=await req('POST','/api/v1/returns',{orderId:proof.id,secret:proof.secret,requestKey:randomUUID(),kind,reason:'Please review this order request'});assert.equal(r.statusCode,200,r.body);return r.json();}
async function review(r:any,action:string,extra:Record<string,unknown>={}){const result=await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action,...extra},admin);assert.equal(result.statusCode,200,result.body);return result.json();}
async function deliver(id:string){for(const [version,status] of [[1,'confirmed'],[2,'shipped'],[3,'delivered']] as const){const r=await req('PUT','/api/v1/admin/orders/'+id,{version,status,...(status==='shipped'?{tracking:{carrier:'Test courier',number:'TRACK-123'}}:{}),...(status==='delivered'?{paymentCollected:true}:{})},admin);assert.equal(r.statusCode,200,r.body);}}
const stock=async()=> (await db.select().from(s.inventory).where(eq(s.inventory.variantId,'variant-1')))[0].available;
before(async()=>{await migrateTestDb(pg);await seedData(db,JSON.parse(await readFile(new URL('../../../database/seeds.json',import.meta.url),'utf8')));await db.insert(s.adminUsers).values([{id:'accounts-owner',email:'owner@example.test',name:'Owner',passwordHash:await hashPassword('Admin-password-12345')},{id:'accounts-viewer',email:'viewer@example.test',name:'Viewer',role:'viewer',passwordHash:await hashPassword('Admin-password-12345')}]);app=await createApp(catalogueRepository(db),{rateLimit:false,orders,payments:settlements,returns,mail,customers:{service:customers,production:false,sameSite:'lax',sessionHours:24,emailMode:'local'},admin:{repo:adminRepository(db),production:false,sameSite:'lax',sessionHours:8,media:mediaStore({driver:'local',localDir:'.data/unused-accounts',publicUrl:'http://localhost:3001/media',production:false})}});const login=await req('POST','/api/v1/admin/login',{email:'owner@example.test',password:'Admin-password-12345'});admin={cookie:String(login.headers['set-cookie']).split(';')[0],csrf:login.json().csrfToken};});
beforeEach(async()=>{await pg.exec('TRUNCATE customers CASCADE; TRUNCATE orders CASCADE; TRUNCATE email_outbox; UPDATE inventory SET available=12; UPDATE products SET version=1;');remotes.clear();payments.clear();refunds.clear();posts=0;uncertain=false;pending=false;});
after(async()=>{await app.close();await pg.close();});

test('registration hashes passwords, encrypts mail tokens and never overwrites an existing account',async()=>{const body={email:'customer@example.test',name:'Customer',password:'Account-password-12345'},first=await req('POST','/api/v1/account/register',body);assert.equal(first.statusCode,200);const code=await token(body.email),row=(await db.select().from(s.customers))[0];assert.ok(!first.body.includes(code));assert.ok(row.passwordHash.startsWith('scrypt$'));assert.equal(row.verifiedAt,null);assert.ok(!(await db.select().from(s.emailOutbox))[0].encryptedPayload!.includes(code));assert.equal((await req('POST','/api/v1/account/register',{...body,password:'Other-password-12345'})).body,first.body);assert.equal((await db.select().from(s.customers))[0].passwordHash,row.passwordHash);assert.equal((await mail.list()).length,1);});
test('guest orders link only after mailbox verification and unrelated accounts cannot access them',async()=>{const proof=await place(),otherOrder=await place('other@example.test'),auth=await account('customer@example.test',false);assert.equal((await req('GET','/api/v1/account/orders',undefined,auth)).statusCode,403);assert.equal((await db.select().from(s.orders).where(eq(s.orders.id,proof.id)))[0].customerId,null);const code=await token('customer@example.test');assert.equal((await req('POST','/api/v1/account/verify',{token:code})).statusCode,200);const list=await req('GET','/api/v1/account/orders',undefined,auth);assert.equal(list.json().items.length,1);assert.equal(list.json().items[0].id,proof.id);assert.equal((await req('GET','/api/v1/account/orders/'+otherOrder.id,undefined,auth)).statusCode,404);const other=await account('other@example.test');assert.equal((await req('GET','/api/v1/account/orders/'+proof.id,undefined,other)).statusCode,404);assert.equal((await req('POST','/api/v1/account/verify',{token:code})).statusCode,400);});
test('cookies are HTTP-only, sessions are hashed and writes require origin and CSRF; logout revokes access',async()=>{const auth=await account(),login=await req('POST','/api/v1/account/login',{email:'customer@example.test',password:'Account-password-12345'});assert.match(String(login.headers['set-cookie']),/HttpOnly/);assert.match(String(login.headers['set-cookie']),/SameSite=Lax/);assert.ok(!(await db.select().from(s.customerSessions)).some(r=>auth.cookie.includes(r.tokenHash)));assert.equal((await req('POST','/api/v1/account/logout',{}, {cookie:auth.cookie})).statusCode,403);assert.equal((await app.inject({method:'POST',url:'/api/v1/account/logout',payload:{},headers:{origin:'https://evil.test',cookie:auth.cookie,'x-csrf-token':auth.csrf}})).statusCode,403);assert.equal((await req('POST','/api/v1/account/logout',{},auth)).statusCode,200);assert.equal((await req('GET','/api/v1/account/session',undefined,auth)).json().user,null);});
test('single-use password reset hides account existence, changes the password and revokes all sessions',async()=>{const auth=await account();const a=await req('POST','/api/v1/account/forgot-password',{email:'customer@example.test'}),b=await req('POST','/api/v1/account/forgot-password',{email:'missing@example.test'});assert.equal(a.body,b.body);const code=await token('customer@example.test','reset');assert.equal((await req('POST','/api/v1/account/reset-password',{token:code,password:'New-password-12345'})).statusCode,200);assert.equal((await req('GET','/api/v1/account/orders',undefined,auth)).statusCode,401);assert.equal((await req('POST','/api/v1/account/login',{email:'customer@example.test',password:'Account-password-12345'})).statusCode,401);assert.equal((await req('POST','/api/v1/account/login',{email:'customer@example.test',password:'New-password-12345'})).statusCode,200);assert.equal((await req('POST','/api/v1/account/reset-password',{token:code,password:'Other-password-12345'})).statusCode,400);});
test('tokens expire and cannot switch purpose; repeated bad logins lock accounts and session expiry blocks access',async()=>{const auth=await account('customer@example.test',false),code=await token('customer@example.test');assert.equal((await req('POST','/api/v1/account/reset-password',{token:code,password:'New-password-12345'})).statusCode,400);await db.update(s.customerTokens).set({expiresAt:new Date(Date.now()-1000)});assert.equal((await req('POST','/api/v1/account/verify',{token:code})).statusCode,400);for(let i=0;i<5;i++)await req('POST','/api/v1/account/login',{email:'customer@example.test',password:'Wrong-password-12345'});assert.equal((await req('POST','/api/v1/account/login',{email:'customer@example.test',password:'Account-password-12345'})).statusCode,401);await db.update(s.customerSessions).set({expiresAt:new Date(Date.now()-1000)});assert.equal((await req('GET','/api/v1/account/orders',undefined,auth)).statusCode,401);});
test('order emails generate once per durable event and include snapshots and dispatch tracking',async()=>{const proof=await place();await mail.tick();await mail.tick();let list=await mail.list();assert.equal(list.length,1);assert.equal(list[0].state,'preview');const text=(await mail.preview(list[0].id)).text;assert.match(text,/Tulip Bloom Box/);assert.match(text,/₹878/);assert.match(text,/TEST ORDER/);await deliver(proof.id);await mail.tick();list=await mail.list();assert.equal(list.length,4);const dispatch=(await mail.preview(list.find(m=>m.subject.includes('dispatched'))!.id)).text;assert.match(dispatch,/TRACK-123/);assert.ok(!dispatch.includes(proof.secret));});
test('email retries preserve provider identity, remove accepted payload and hold old ambiguous sends for review',async()=>{const seen:string[]=[];const provider=emailService(db,{driver:'resend',siteUrl:origin,encryptionKey:'a'.repeat(64),from:'store@example.test',production:true,send:async id=>{seen.push(id);if(seen.length===1)throw Error('lost response');return 'provider-id';}});await provider.enqueue(db,'delivery','customer@example.test','Test','Private content');await provider.tick();await db.update(s.emailOutbox).set({availableAt:new Date(Date.now()-1000)});await provider.tick();assert.equal(seen.length,2);assert.equal(seen[0],seen[1]);const row=(await db.select().from(s.emailOutbox))[0];assert.equal(row.state,'sent');assert.equal(row.encryptedPayload,null);await assert.rejects(()=>provider.preview(row.id));await provider.enqueue(db,'old','customer@example.test','Old','content');await db.update(s.emailOutbox).set({firstAttemptAt:new Date(Date.now()-24*3600000)}).where(eq(s.emailOutbox.eventKey,'old'));await provider.tick();assert.equal((await db.select().from(s.emailOutbox).where(eq(s.emailOutbox.eventKey,'old')))[0].state,'review');assert.equal(seen.length,2);});
test('email previews require admin writer access and queue processing requires CSRF',async()=>{await account();const id=(await mail.list())[0].id;assert.equal((await req('GET','/api/v1/admin/emails/'+id+'/preview')).statusCode,401);const login=await req('POST','/api/v1/admin/login',{email:'viewer@example.test',password:'Admin-password-12345'}),viewer={cookie:String(login.headers['set-cookie']).split(';')[0],csrf:login.json().csrfToken};assert.equal((await req('GET','/api/v1/admin/emails/'+id+'/preview',undefined,viewer)).statusCode,403);assert.equal((await req('POST','/api/v1/admin/emails/process',{}, {cookie:admin.cookie})).statusCode,403);assert.equal((await req('POST','/api/v1/admin/emails/process',{},admin)).statusCode,200);});
test('guest requests require proof, retries persist one case and account requests require verified ownership',async()=>{const proof=await place(),body={orderId:proof.id,requestKey:randomUUID(),kind:'cancel',reason:'Please cancel this order',secret:proof.secret};assert.equal((await req('POST','/api/v1/returns',{...body,secret:'0'.repeat(64)})).statusCode,404);const a=await req('POST','/api/v1/returns',body),b=await req('POST','/api/v1/returns',body);assert.equal(a.statusCode,200);assert.equal(a.json().id,b.json().id);assert.equal((await db.select().from(s.returnRequests)).length,1);const other=await account('other@example.test');assert.equal((await req('POST','/api/v1/account/returns',{orderId:proof.id,requestKey:randomUUID(),kind:'cancel',reason:'Please cancel this order'},other)).statusCode,404);assert.equal((await req('POST','/api/v1/orders/returns',proof)).json()[0].refundId,undefined);});
test('unpaid COD cancellation approval holds dispatch and closing restores stock once',async()=>{const proof=await place();let r=await requestReturn(proof);assert.equal((await req('PUT','/api/v1/admin/orders/'+proof.id,{version:1,status:'confirmed'},admin)).statusCode,200);assert.equal((await req('PUT','/api/v1/admin/orders/'+proof.id,{version:2,status:'shipped'},admin)).statusCode,409);r=await review(r,'approve');assert.equal(await stock(),11);r=await review(r,'close');assert.equal(r.state,'closed');assert.equal(await stock(),12);assert.equal((await db.select().from(s.orders))[0].status,'cancelled');assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'close'},admin)).statusCode,409);assert.equal(await stock(),12);});
test('COD returns require approval and receipt; restocking and confirmed external refund are separate once-only steps',async()=>{const proof=await place();await deliver(proof.id);let r=await requestReturn(proof,'return');assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'restock'},admin)).statusCode,409);r=await review(r,'approve');r=await review(r,'receive');assert.equal(await stock(),11);r=await review(r,'restock');assert.equal(await stock(),12);r=await review(r,'manual-refund',{reference:'TEST-REFUND-123'});assert.equal(r.state,'refunded');assert.equal((await db.select().from(s.orders))[0].paymentStatus,'refunded');r=await review(r,'close');assert.equal(r.state,'closed');assert.equal(await stock(),12);});
test('return window and stale admin versions prevent invalid review',async()=>{const proof=await place();await deliver(proof.id);await db.update(s.orderEvents).set({createdAt:new Date(Date.now()-15*86400000)}).where(eq(s.orderEvents.status,'delivered'));assert.equal((await req('POST','/api/v1/returns',{orderId:proof.id,secret:proof.secret,requestKey:randomUUID(),kind:'return',reason:'Return all items please'})).statusCode,409);await db.update(s.orderEvents).set({createdAt:new Date()}).where(eq(s.orderEvents.status,'delivered'));const r=await requestReturn(proof,'return');assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'approve'})).statusCode,401);await review(r,'approve');assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'receive'},admin)).statusCode,409);});
test('online refund processing verifies full amounts before refund status, without automatic restock',async()=>{const proof=await place('customer@example.test',true);let r=await requestReturn(proof);r=await review(r,'approve');r=await review(r,'refund');assert.equal(r.state,'refunded');assert.equal(posts,1);assert.equal(await stock(),11);assert.equal((await db.select().from(s.orders))[0].paymentStatus,'refunded');r=await review(r,'close');assert.equal(await stock(),12);await settlements.reconcile(proof.id);assert.equal((await db.select().from(s.orders))[0].paymentStatus,'refunded');});
test('uncertain provider refund response recovers by stable receipt and never posts a second refund',async()=>{const proof=await place('customer@example.test',true);let r=await requestReturn(proof);r=await review(r,'approve');uncertain=true;assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'refund'},admin)).statusCode,500);assert.equal(posts,1);uncertain=false;await returns.tick();assert.equal((await returns.detail(r.id)).state,'refunded');assert.equal(posts,1);assert.equal(await stock(),11);});
test('pending, failed and mismatched refunds never mark orders refunded or automatically refund again',async()=>{const proof=await place('customer@example.test',true);let r=await requestReturn(proof);r=await review(r,'approve');pending=true;r=await review(r,'refund');assert.equal(r.state,'refund_pending');assert.equal((await db.select().from(s.orders))[0].paymentStatus,'review');const remote=refunds.get(r.refundId)!;remote.status='failed';r=await review(r,'check');assert.equal(r.refundState,'failed');remote.status='processed';remote.amount=1;assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'check'},admin)).statusCode,409);assert.equal((await db.select().from(s.orders))[0].paymentStatus,'review');assert.equal(posts,1);});
test('existing matching external refunds can be reconciled without issuing more money',async()=>{const proof=await place('customer@example.test',true);let r=await requestReturn(proof);r=await review(r,'approve');const p=[...payments.values()][0];p.amount_refunded=p.amount;refunds.set('rfnd_External',{id:'rfnd_External',payment_id:p.id,amount:p.amount,currency:'INR',status:'processed',receipt:null,notes:{}});r=await review(r,'adopt-refund',{reference:'rfnd_External'});assert.equal(r.state,'refunded');assert.equal(posts,0);});
test('account payment checks enforce ownership and CSRF and never disclose guest secrets',async()=>{const proof=await place('customer@example.test',true),auth=await account(),other=await account('other@example.test'),url='/api/v1/account/orders/'+proof.id+'/payment/status';assert.equal((await req('POST',url,{}, {cookie:auth.cookie})).statusCode,403);assert.equal((await req('POST',url,{},other)).statusCode,404);const r=await req('POST',url,{},auth);assert.equal(r.statusCode,200);assert.ok(!r.body.includes(proof.secret));assert.equal((await req('GET','/api/v1/account/orders/'+proof.id,undefined,auth)).json().address,undefined);});

test('migration 005 preserves existing COD orders, administrators, payment sessions and stock',async()=>{
 const prior=new PGlite();try{
  for(const file of ['001_catalogue.sql','002_admin.sql','003_orders.sql','004_payments.sql'])await prior.exec(await readFile(new URL('../../../database/migrations/'+file,import.meta.url),'utf8'));
  await seedData(drizzle(prior,{schema:s}) as unknown as CommerceDb,JSON.parse(await readFile(new URL('../../../database/seeds.json',import.meta.url),'utf8')));await prior.query("UPDATE inventory SET available=7 WHERE variant_id='variant-1'");
  await prior.query("INSERT INTO admin_users(id,email,name,password_hash) VALUES('old-owner','old@example.test','Owner','unchanged-hash')");
  await prior.query("INSERT INTO orders(id,number,checkout_key,receipt_secret_hash,request_hash,mode,status,customer,address,totals,total_paise,delivery,gift_wrap) VALUES('old-order','OLD-ORDER','old-key','private-hash','request-hash','test','cancelled','{}','{}','{}',12345,'standard',false)");
  await prior.query("INSERT INTO payment_sessions(order_id,key_id,gateway_order_id,state) VALUES('old-order','rzp_test_old','order_Old','ready')");
  await prior.exec(await readFile(new URL('../../../database/migrations/005_accounts_returns.sql',import.meta.url),'utf8'));
  assert.equal((await prior.query<{available:number}>("SELECT available FROM inventory WHERE variant_id='variant-1'")).rows[0].available,7);
  const row=(await prior.query<{customer_id:string|null,total_paise:number,payment_status:string}>("SELECT customer_id,total_paise,payment_status FROM orders WHERE id='old-order'")).rows[0];assert.equal(row.customer_id,null);assert.equal(Number(row.total_paise),12345);assert.equal(row.payment_status,'unpaid');assert.equal((await prior.query<{password_hash:string}>("SELECT password_hash FROM admin_users WHERE id='old-owner'")).rows[0].password_hash,'unchanged-hash');assert.equal((await prior.query<{gateway_order_id:string}>("SELECT gateway_order_id FROM payment_sessions WHERE order_id='old-order'")).rows[0].gateway_order_id,'order_Old');
 }finally{await prior.close();}
});

test('ordinary COD cancellation cannot restore stock again after approved cancellation restocking',async()=>{const proof=await place();let r=await requestReturn(proof);r=await review(r,'approve');r=await review(r,'restock');assert.equal(await stock(),12);const version=(await db.select().from(s.orders))[0].version;assert.equal((await req('PUT','/api/v1/admin/orders/'+proof.id,{version,status:'cancelled'},admin)).statusCode,200);assert.equal(await stock(),12);r=await review(r,'close');assert.equal(await stock(),12);assert.equal(r.state,'closed');});
test('late COD collection updates an active return refund amount and invalidates stale reviews',async()=>{const proof=await place();for(const [version,status] of [[1,'confirmed'],[2,'shipped'],[3,'delivered']] as const)assert.equal((await req('PUT','/api/v1/admin/orders/'+proof.id,{version,status},admin)).statusCode,200);let r=await requestReturn(proof,'return');assert.equal(r.amountPaise,0);assert.equal((await req('PUT','/api/v1/admin/orders/'+proof.id,{version:4,status:'delivered',paymentCollected:true},admin)).statusCode,200);assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'approve'},admin)).statusCode,409);r=await returns.detail(r.id);assert.equal(r.amountPaise,87800);r=await review(r,'approve');r=await review(r,'receive');assert.equal((await req('POST','/api/v1/admin/returns/'+r.id+'/review',{version:r.version,action:'close'},admin)).statusCode,409);r=await review(r,'manual-refund',{reference:'TEST-LATE-COLLECTION'});assert.equal(r.state,'refunded');});


test('test recipient restriction preserves demo mail and does not starve allowed mail',async()=>{
 const seen:string[]=[];
 const provider=emailService(db,{driver:'resend',siteUrl:origin,encryptionKey:'a'.repeat(64),from:'onboarding@resend.dev',testRecipient:' Allowed@example.test ',production:true,send:async(_id,recipient)=>{seen.push(recipient);return 'test-provider';}});
 for(let i=0;i<12;i++)await provider.enqueue(db,'demo-'+i,'demo@example.test','Demo','Keep this payload');
 await provider.enqueue(db,'allowed','allowed@example.test','Allowed','Own mailbox');
 await provider.tick();await provider.tick();
 assert.deepEqual(seen,['allowed@example.test']);
 const rows=await db.select().from(s.emailOutbox);
 for(const row of rows.filter(r=>r.eventKey.startsWith('demo-'))){assert.equal(row.state,'queued');assert.equal(row.attempts,0);assert.equal(row.firstAttemptAt,null);assert.ok(row.encryptedPayload);}
 assert.equal(rows.find(r=>r.eventKey==='allowed')!.state,'sent');
 const unrestricted=emailService(db,{driver:'resend',siteUrl:origin,encryptionKey:'a'.repeat(64),from:'store@example.test',production:true,send:async(_id,recipient)=>{seen.push(recipient);return 'verified-provider';}});
 await unrestricted.tick();assert.equal(seen.length,11);
});

test('Resend sandbox sender refuses to start without a valid test recipient',()=>{
 const options={driver:'resend' as const,siteUrl:origin,encryptionKey:'a'.repeat(64),from:'onboarding@resend.dev',production:true};
 assert.throws(()=>emailService(db,options),/requires a test recipient/);
 assert.throws(()=>emailService(db,{...options,testRecipient:'invalid'}),/Invalid test email recipient/);
});
