import { before,after,beforeEach,test } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac,randomUUID,randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';
import { eq } from 'drizzle-orm';
import { migrateTestDb } from '../../../scripts/migrate-test-db.js';
import { createApp } from '../src/app.js';
import { catalogueRepository } from '../src/catalogue.js';
import { orderRepository } from '../src/orders.js';
import { paymentService } from '../src/payments.js';
import { adminRepository } from '../src/admin-repository.js';
import { hashPassword } from '../src/password.js';
import { mediaStore } from '../src/media.js';
import { seedData } from '../src/seed-data.js';
import { validSignature,type PaymentGateway,type GatewayOrder,type GatewayPayment } from '../src/razorpay.js';
import * as s from '../src/schema.js';
const pg=new PGlite(),db=drizzle(pg,{schema:s}) as unknown as NodePgDatabase<typeof s>,origin='http://localhost:4321';
let app:Awaited<ReturnType<typeof createApp>>,service:ReturnType<typeof paymentService>,auth:{cookie:string,csrf:string},created=0,timeoutAfterCreation=false,offline=false;
const remoteOrders=new Map<string,GatewayOrder>(),remotePayments=new Map<string,GatewayPayment>();
const gateway:PaymentGateway={keyId:'rzp_test_testing',keySecret:'test-api-secret',webhookSecrets:['test-webhook-secret-12345','old-webhook-secret-12345'],
 create:async(receipt,amount)=>{created++;const order={id:'order_'+receipt.replaceAll('-',''),amount,currency:'INR',receipt,notes:{local_order_id:receipt},status:'created'};remoteOrders.set(order.id,order);if(timeoutAfterCreation)throw new Error('Simulated uncertain provider response');return order;},
 find:async receipt=>{if(offline)throw new Error('offline');return [...remoteOrders.values()].filter(o=>o.receipt===receipt);},
 order:async id=>{if(offline)throw new Error('offline');const order=remoteOrders.get(id);assert.ok(order);return order;},
 payment:async id=>{if(offline)throw new Error('offline');const p=remotePayments.get(id);assert.ok(p);return p;},
 payments:async id=>{if(offline)throw new Error('offline');return [...remotePayments.values()].filter(p=>p.order_id===id);},
};
const input=()=>({expectedMode:'test',checkoutKey:randomUUID(),receiptSecret:randomBytes(32).toString('hex'),items:[{variantId:'variant-1',quantity:1}],coupon:'',giftWrap:false,delivery:'standard',paymentMethod:'online',customer:{name:'Payment Customer',email:'customer@example.test',phone:'9876543210'},address:{line1:'123 Test Road',line2:'',city:'Bengaluru',state:'Karnataka',postalCode:'560001',country:'IN'},expectedTotalPaise:83805});
const post=(url:string,body:unknown)=>app.inject({method:'POST',url,payload:JSON.stringify(body),headers:{origin,'content-type':'application/json'}});
async function setup(){const body=input();const r=await post('/api/v1/orders',body);assert.equal(r.statusCode,201,r.body);const access={id:r.json().id,secret:body.receiptSecret};const start=await post('/api/v1/payments/start',access);assert.equal(start.statusCode,200,start.body);return {body,order:r.json(),access,session:start.json()};}
function payment(remoteId:string,status='captured',amount=83805,id='pay_Test1'){const p={id,order_id:remoteId,amount,currency:'INR',status,captured:status==='captured',amount_refunded:0};remotePayments.set(id,p);if(status==='captured')remoteOrders.get(remoteId)!.status='paid';return p;}
const signature=(orderId:string,paymentId:string)=>createHmac('sha256',gateway.keySecret).update(orderId+'|'+paymentId).digest('hex');
async function webhook(remoteId:string|null,event='payment.captured',eventId:string=randomUUID(),secret=gateway.webhookSecrets[0]){const raw=JSON.stringify({event,payload:event.startsWith('refund.')?{refund:{entity:{payment_id:'pay_Test1'}}}:{payment:{entity:{order_id:remoteId}}}},null,2);return app.inject({method:'POST',url:'/api/v1/payments/razorpay/webhook',payload:raw,headers:{'content-type':'application/json','x-razorpay-event-id':eventId,'x-razorpay-signature':createHmac('sha256',secret).update(raw).digest('hex')}});}
async function stock(){return (await db.select().from(s.inventory).where(eq(s.inventory.variantId,'variant-1')))[0].available;}
before(async()=>{await migrateTestDb(pg);await seedData(db,JSON.parse(await readFile(new URL('../../../database/seeds.json',import.meta.url),'utf8')));const orders=orderRepository(db,{mode:'test',pinPrefixes:[],onlineEnabled:true});service=paymentService(db,orders,gateway);await db.insert(s.adminUsers).values({id:'payment-admin',name:'Owner',email:'owner@example.test',passwordHash:await hashPassword('Test-password-12345')});app=await createApp(catalogueRepository(db),{rateLimit:false,orders,payments:service,admin:{repo:adminRepository(db),production:false,sameSite:'lax',sessionHours:8,media:mediaStore({driver:'local',localDir:'.data/unused-payments',publicUrl:'http://localhost:3001/media',production:false})}});const login=await post('/api/v1/admin/login',{email:'owner@example.test',password:'Test-password-12345'});auth={cookie:String(login.headers['set-cookie']).split(';')[0],csrf:login.json().csrfToken};});
beforeEach(async()=>{await pg.exec('TRUNCATE orders CASCADE; TRUNCATE payment_webhook_events; UPDATE inventory SET available=12; UPDATE products SET version=1;');remoteOrders.clear();remotePayments.clear();created=0;timeoutAfterCreation=false;offline=false;});
after(async()=>{await app.close();await pg.close();});
test('online order reserves stock and uses server-calculated prepaid savings; session retries create one gateway order',async()=>{const {access,session,order}=await setup();assert.equal(order.paymentStatus,'pending');assert.equal(order.totals.prepaidDiscountPaise,3995);assert.equal(await stock(),11);assert.ok(order.paymentExpiresAt);assert.equal(session.amountPaise,83805);assert.equal(session.keyId,gateway.keyId);assert.equal(session.keySecret,undefined);assert.equal((await post('/api/v1/payments/start',access)).json().gatewayOrderId,session.gatewayOrderId);assert.equal(created,1);});
test('receipt secrets, exact origin and checkout callback HMAC are required',async()=>{const {access,session}=await setup();assert.equal((await post('/api/v1/payments/start',{...access,secret:'0'.repeat(64)})).statusCode,404);assert.equal((await app.inject({method:'POST',url:'/api/v1/payments/start',payload:access,headers:{origin:'https://evil.test'}})).statusCode,403);payment(session.gatewayOrderId);const body={...access,razorpay_order_id:session.gatewayOrderId,razorpay_payment_id:'pay_Test1',razorpay_signature:'0'.repeat(64)};assert.equal((await post('/api/v1/payments/verify',body)).statusCode,400);assert.equal(validSignature('x','é'.repeat(64),'secret'),false);assert.equal((await post('/api/v1/payments/verify',{...body,razorpay_order_id:'order_Other',razorpay_signature:signature('order_Other','pay_Test1')})).statusCode,400);});
test('a signed captured callback confirms one order without consuming stock twice',async()=>{const {access,session}=await setup();payment(session.gatewayOrderId);const body={...access,razorpay_order_id:session.gatewayOrderId,razorpay_payment_id:'pay_Test1',razorpay_signature:signature(session.gatewayOrderId,'pay_Test1')};const first=await post('/api/v1/payments/verify',body);assert.equal(first.statusCode,200,first.body);assert.equal(first.json().paymentStatus,'paid');assert.equal(first.json().status,'confirmed');await post('/api/v1/payments/verify',body);assert.equal(await stock(),11);assert.equal((await db.select().from(s.orderEvents)).length,2);});
test('authorized payment is not paid; mismatched amounts/currencies cannot confirm fulfilment',async()=>{const {access,session}=await setup();const p=payment(session.gatewayOrderId,'authorized');const body={...access,razorpay_order_id:session.gatewayOrderId,razorpay_payment_id:p.id,razorpay_signature:signature(session.gatewayOrderId,p.id)};assert.equal((await post('/api/v1/payments/verify',body)).json().paymentStatus,'pending');p.status='captured';p.captured=true;p.amount=1;assert.equal((await post('/api/v1/payments/verify',body)).statusCode,409);p.amount=83805;p.currency='USD';assert.equal((await post('/api/v1/payments/verify',body)).statusCode,409);assert.equal((await db.select().from(s.orders))[0].status,'pending');});
test('raw-body webhook signatures, event IDs and duplicate delivery are enforced',async()=>{const {access,session}=await setup();payment(session.gatewayOrderId);const raw=JSON.stringify({event:'payment.captured',payload:{payment:{entity:{order_id:session.gatewayOrderId}}}},null,2);const compact=JSON.stringify(JSON.parse(raw));const bad=await app.inject({method:'POST',url:'/api/v1/payments/razorpay/webhook',payload:raw,headers:{'content-type':'application/json','x-razorpay-event-id':'bad','x-razorpay-signature':createHmac('sha256',gateway.webhookSecrets[0]).update(compact).digest('hex')}});assert.equal(bad.statusCode,400);assert.equal((await webhook(session.gatewayOrderId,'payment.captured','evt_1')).statusCode,200);assert.equal((await webhook(session.gatewayOrderId,'payment.captured','evt_1')).statusCode,200);assert.equal((await db.select().from(s.paymentWebhookEvents)).length,1);assert.equal((await db.select().from(s.orderEvents)).length,2);assert.equal((await post('/api/v1/orders/receipt',access)).json().paymentStatus,'paid');assert.equal((await webhook(null,'payment.captured','unrelated')).statusCode,200);assert.equal((await db.select().from(s.orderEvents)).length,2);});
test('old webhook secrets validate retries and out-of-order failed events cannot downgrade captured payment',async()=>{const {session}=await setup();payment(session.gatewayOrderId);assert.equal((await webhook(session.gatewayOrderId,'order.paid','paid',gateway.webhookSecrets[1])).statusCode,200);assert.equal((await webhook(session.gatewayOrderId,'payment.failed','failed')).statusCode,200);assert.equal((await db.select().from(s.orders))[0].paymentStatus,'paid');});
test('gateway timeout after creation recovers by receipt without creating a second provider order',async()=>{const body=input(),r=await post('/api/v1/orders',body),access={id:r.json().id,secret:body.receiptSecret};timeoutAfterCreation=true;assert.equal((await post('/api/v1/payments/start',access)).statusCode,500);assert.equal(created,1);timeoutAfterCreation=false;const retry=await post('/api/v1/payments/start',access);assert.equal(retry.statusCode,200,retry.body);assert.equal(created,1);});
test('expired unpaid reservations restore stock once and refuse reopening payment checkout',async()=>{const {access}=await setup();await db.update(s.orders).set({paymentExpiresAt:new Date(Date.now()-1000)}).where(eq(s.orders.id,access.id));const r=await post('/api/v1/payments/status',access);assert.equal(r.json().status,'cancelled',r.body);assert.equal(await stock(),12);await post('/api/v1/payments/status',access);assert.equal(await stock(),12);assert.equal((await post('/api/v1/payments/start',access)).statusCode,409);});
test('provider outage or authorized payment retains stock after the local deadline',async()=>{const {access,session}=await setup();await db.update(s.orders).set({paymentExpiresAt:new Date(Date.now()-1000)}).where(eq(s.orders.id,access.id));offline=true;assert.equal((await post('/api/v1/payments/status',access)).statusCode,500);assert.equal(await stock(),11);offline=false;payment(session.gatewayOrderId,'authorized');assert.equal((await post('/api/v1/payments/status',access)).json().status,'pending');assert.equal(await stock(),11);});
test('late captured payments become review after cancellation and do not fulfil unavailable stock',async()=>{const {access,session}=await setup();await db.update(s.orders).set({paymentExpiresAt:new Date(Date.now()-1000)}).where(eq(s.orders.id,access.id));await post('/api/v1/payments/status',access);payment(session.gatewayOrderId);assert.equal((await webhook(session.gatewayOrderId)).statusCode,200);const row=(await db.select().from(s.orders))[0];assert.equal(row.status,'cancelled');assert.equal(row.paymentStatus,'review');assert.equal(await stock(),12);});
test('refunds are recorded for review and later captured snapshots do not erase the review state',async()=>{const {access,session}=await setup();const p=payment(session.gatewayOrderId);await webhook(session.gatewayOrderId);p.status='refunded';p.amount_refunded=83805;await webhook(session.gatewayOrderId,'refund.processed');assert.equal((await db.select().from(s.orders))[0].paymentStatus,'review');p.status='captured';p.captured=true;p.amount_refunded=0;await webhook(session.gatewayOrderId);assert.equal((await db.select().from(s.orders))[0].paymentStatus,'review');assert.equal(await stock(),11);assert.equal((await post('/api/v1/orders/receipt',access)).json().paymentStatus,'review');});
test('admin cannot fake online cash collection, ship unpaid orders or cancel paid orders without refunds',async()=>{const {access,session}=await setup();const put=(body:unknown)=>app.inject({method:'PUT',url:'/api/v1/admin/orders/'+access.id,payload:JSON.stringify(body),headers:{origin,'content-type':'application/json',cookie:auth.cookie,'x-csrf-token':auth.csrf}});assert.equal((await put({version:1,status:'confirmed'})).statusCode,409);assert.equal((await put({version:1,status:'delivered',paymentCollected:true})).statusCode,400);payment(session.gatewayOrderId);await webhook(session.gatewayOrderId);assert.equal((await put({version:2,status:'cancelled'})).statusCode,409);const r=await put({version:2,status:'shipped'});assert.equal(r.statusCode,200,r.body);assert.equal(r.json().paymentStatus,'paid');});
test('persistent reconciliation checks unstarted expired orders and catches captures without a browser callback',async()=>{const {session}=await setup();payment(session.gatewayOrderId);await service.tick();assert.equal((await db.select().from(s.orders))[0].paymentStatus,'paid');const body=input(),r=await post('/api/v1/orders',body);await db.update(s.orders).set({paymentExpiresAt:new Date(Date.now()-1000)}).where(eq(s.orders.id,r.json().id));await service.tick();assert.equal((await db.select().from(s.orders).where(eq(s.orders.id,r.json().id)))[0].status,'cancelled');assert.equal(await stock(),11);});
test('migration 004 preserves COD orders, accounts and inventory while marking previously cancelled stock as released',async()=>{
 const previous=new PGlite();try{
  for(const file of ['001_catalogue.sql','002_admin.sql','003_orders.sql'])await previous.exec(await readFile(new URL('../../../database/migrations/'+file,import.meta.url),'utf8'));
  const oldDb=drizzle(previous,{schema:s}) as unknown as NodePgDatabase<typeof s>;await seedData(oldDb,JSON.parse(await readFile(new URL('../../../database/seeds.json',import.meta.url),'utf8')));
  await previous.query("INSERT INTO admin_users(id,email,name,password_hash) VALUES ('previous-owner','owner@example.test','Owner','unchanged-password-hash')");
  await previous.query("INSERT INTO orders(id,number,checkout_key,receipt_secret_hash,request_hash,mode,status,customer,address,totals,total_paise,delivery,gift_wrap) VALUES ('previous-order','ORD-PREVIOUS','previous-key','secret-hash','request-hash','test','cancelled','{}','{}','{}',12345,'standard',false)");
  await previous.query("UPDATE inventory SET available=7 WHERE variant_id='variant-1'");await previous.exec(await readFile(new URL('../../../database/migrations/004_payments.sql',import.meta.url),'utf8'));
  const row=(await previous.query<{payment_method:string,payment_status:string,inventory_released:boolean,total_paise:string}>("SELECT payment_method,payment_status,inventory_released,total_paise FROM orders WHERE id='previous-order'")).rows[0];assert.equal(row.payment_method,'cod');assert.equal(row.payment_status,'unpaid');assert.equal(row.inventory_released,true);assert.equal(Number(row.total_paise),12345);
  assert.equal((await previous.query<{password_hash:string}>("SELECT password_hash FROM admin_users WHERE id='previous-owner'")).rows[0].password_hash,'unchanged-password-hash');assert.equal((await previous.query<{available:number}>("SELECT available FROM inventory WHERE variant_id='variant-1'")).rows[0].available,7);
 }finally{await previous.close();}
});
test('admin reconciliation requires the existing authenticated writer and CSRF token',async()=>{const {access}=await setup();const url='/api/v1/admin/orders/'+access.id+'/reconcile';assert.equal((await post(url,{})).statusCode,401);assert.equal((await app.inject({method:'POST',url,payload:{},headers:{origin,cookie:auth.cookie}})).statusCode,403);const r=await app.inject({method:'POST',url,payload:{},headers:{origin,cookie:auth.cookie,'x-csrf-token':auth.csrf}});assert.equal(r.statusCode,200,r.body);assert.equal(r.json().payment.gatewayOrderId.startsWith('order_'),true);});
